v4l: xilinx: hls: Fix the uapi header license
commit a55b16029bbab8a4f3d9d1688758b41257ddb9e8 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>