ARM: imx: Remove unused pmu_release_id label
Due to the SDK changes, the stable commit 12ac3b0ab837 ("ARM: imx: Check
return value of devm_kasprintf in imx_mmdc_perf_init") doesn't apply to
the nxp branches. But part of this commit was merged mistakenly. Revert
these changes to fix the following build errors:
  arch/arm/mach-imx/mmdc.c: In function ‘imx_mmdc_perf_init’:
  arch/arm/mach-imx/mmdc.c:528:1: error: label ‘pmu_release_id’ defined but not used [-Werror=unused-label]
    528 | pmu_release_id:
        | ^~~~~~~~~~~~~~

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>