net: ethernet: ti: prueth: Fix compile error when CONFIG_HSR is not set
commit 7a341da29f4a5d596e459ab47ee1f3f834af1497 from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

Fix the following compile error when CONFIG_HSR is not set
prueth_core.c:2846:9: error: ‘struct net_device’ has no member
named ‘lredev_ops’;

Signed-off-by: Kishon Vijay Abraham I <kishon@ti.com>
Signed-off-by: Vignesh Raghavendra <vigneshr@ti.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>