MGS-4530-2 disable busfreq-imx to fix L4.19 dash build
commit 4877b1bbe1c9fca5a41573a8bc5fc81ceecd2667 from
https://github.com/nxp-imx/linux-imx.git

gc_hal_kernel_platform_imx.c:90:14: fatal error: linux/busfreq-imx.h: No such file or directory
 #    include <linux/busfreq-imx.h>

Signed-off-by: Xianzhong <xianzhong.li@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>