v4l: xilinx: sdi: Fix the uapi header license
commit 592f056d5386fa48942e639a6cc820f808a1e62b from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>