crypto: octeontx2: put the function definition before the reference
commit d2a3cbda0b7f(drivers: crypto: add support for OCTEONTX2 CPT engine)
put function sso_pf_func_ovrd_show() and sso_pf_func_ovrd_store() after
the reference, will cause build issue below. Move the function definition
before the reference to fix this.

drivers/crypto/marvell/octeontx2/otx2_cptpf_main.c:532:23: error: 'sso_pf_func_ovrd_store' undeclared here (not in a function)
  532 | static DEVICE_ATTR_RW(sso_pf_func_ovrd);
      |                       ^~~~~~~~~~~~~~~~

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>