LF-1011-22 gpu: drm: bridge: dsim: remove the using of bridge->next
commit 0f1c3ed97a5c46c4d1325eda4d673fd37a0b5b51 from
https://source.codeaurora.org/external/imx/linux-imx

API changed since:
05193dc38197 ("drm/bridge: Make the bridge chain a double-linked list")

../drivers/gpu/drm/bridge/sec-dsim.c: In function ‘sec_mipi_dsim_bridge_attach’:
../drivers/gpu/drm/bridge/sec-dsim.c:855:34: error: ‘struct drm_bridge’ has no member named ‘next’
  855 |  WARN_ON(bridge == next || bridge->next || dsim->next);
      |                                  ^~
../include/asm-generic/bug.h:113:25: note: in definition of macro ‘WARN_ON’
  113 |  int __ret_warn_on = !!(condition);    \
      |                         ^~~~~~~~~
../drivers/gpu/drm/bridge/sec-dsim.c:868:8: error: ‘struct drm_bridge’ has no member named ‘next’
  868 |  bridge->next = next;
      |        ^~
../drivers/gpu/drm/bridge/sec-dsim.c: In function ‘sec_mipi_dsim_connector_get_modes’:
../drivers/gpu/drm/bridge/sec-dsim.c:1801:9: error: too few arguments to function ‘drm_panel_get_modes’
 1801 |  return drm_panel_get_modes(dsim->panel);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>