soc: marvell: add missing header needed by linux/soc/marvell/octeontx2/asm.h
commit ecd71fc49abf(octeontx2-pf: Use CQ_OP_STATUS register for CQE
count) added function otx2_atomic64_fetch_add(), but didn't add the
corresponding header file, which cause below compilation problems.
Add missing header in file include/linux/soc/marvell/octeontx2/asm.h.

include/linux/soc/marvell/octeontx2/asm.h:38:15: error: unknown type name 'u64'
   38 | static inline u64 otx2_atomic64_fetch_add(u64 incr, u64 *ptr)
      |               ^~~
include/linux/soc/marvell/octeontx2/asm.h:38:43: error: unknown type name 'u64'
   38 | static inline u64 otx2_atomic64_fetch_add(u64 incr, u64 *ptr)
      |                                           ^~~
include/linux/soc/marvell/octeontx2/asm.h:38:53: error: unknown type name 'u64'
   38 | static inline u64 otx2_atomic64_fetch_add(u64 incr, u64 *ptr)
      |                                                     ^~~

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>