gpu:Remove dma.h to avoid Linux 5.x build problem
commit c3c2412b8ef4b7c55464052d0d1afcfacc3a4860 from
https://github.com/nxp-imx/linux-imx.git

Log:
    ../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:87:17:
fatal error: dma.h: No such file or directory
     #include <dma.h>
                     ^
    compilation terminated.
    ../scripts/Makefile.build:280: recipe for target
'drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.o' failed
    make[4]: ***
[drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.o] Error 1

Signed-off-by: Minjie Zhuang<minjie.zhuang@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>