MLK-21876-5 gpu: drm: dpu: fix build for next-20190524 upgrade
commit cff216be91d05997572679d776795b82bac27f9d from
https://source.codeaurora.org/external/imx/linux-imx

In file included from ../drivers/gpu/drm/imx/dpu/dpu-crtc.h:19:0,
                 from ../drivers/gpu/drm/imx/dpu/dpu-crtc.c:29:
../drivers/gpu/drm/imx/dpu/dpu-plane.h:19:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"
                     ^
compilation terminated.
../scripts/Makefile.build:278: recipe for target 'drivers/gpu/drm/imx/dpu/dpu-crtc.o' failed
make[6]: *** [drivers/gpu/drm/imx/dpu/dpu-crtc.o] Error 1
../scripts/Makefile.build:489: recipe for target 'drivers/gpu/drm/imx/dpu' failed
make[5]: *** [drivers/gpu/drm/imx/dpu] Error 2

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>