SPEAr: fix missing include file system_misc.h
To fix following compile error:
...
In function 'spear_pm_prepare':
error: implicit declaration of function 'disable_hlt'
error: implicit declaration of function 'enable_hlt'
...

Signed-off-by: Liming Wang <liming.wang@windriver.com>