SPEAr: add missing definition for spear_smi
To fix following compile error:
...
In function 'spear1310_reva_evb_init':
arch/arm/mach-spear13xx/spear1310_reva_evb.c:529:2:
  error: implicit declaration of function 'smi_init_board_info'
...

Signed-off-by: Liming Wang <liming.wang@windriver.com>