dt-bindings: pinctrl: k3: Introduce pinmux definitions for J784s4
commit 41a4112cb996bbdec8e929019b5f208c51c69c0d from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

commit a0c01bc565332cff9183bd8a17b4db94732d645d upstream.

Add pinctrl macros for J784s4 SoC. These macro definitions are
similar to that of J721s2, but adding new definitions to avoid
any naming confusions in the soc dts files.

checkpatch insists the following error exists:
ERROR: Macros with complex values should be enclosed in parentheses

However, we do not need parentheses enclosing the values for this
macro as we do intend it to generate two separate values as has been
done for other similar platforms.

Signed-off-by: Hari Nagalla <hnagalla@ti.com>
Signed-off-by: Apurva Nandan <a-nandan@ti.com>
Acked-by: Rob Herring <robh@kernel.org>
Acked-by: Linus Walleij <linus.walleij@linaro.org>
Signed-off-by: Vignesh Raghavendra <vigneshr@ti.com>
Link: https://lore.kernel.org/r/20230112142725.77785-3-a-nandan@ti.com
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>