LF-1011-21 gpu: drm: bridge: ite6263: switch to use i2c_new_dummy_device
commit 7532ed5a3b24251e34f8a227b43a4edeca39ee01 from
https://github.com/nxp-imx/linux-imx.git

The old one was removed since:
2c2f00ab1641 ("i2c: remove i2c_new_dummy() API")

../drivers/gpu/drm/bridge/it6263.c: In function ‘it6263_probe’:
../drivers/gpu/drm/bridge/it6263.c:879:21: error: implicit declaration of function ‘i2c_new_dummy’ [-Werror=implicit-function-declaration]
  879 |  it6263->lvds_i2c = i2c_new_dummy(client->adapter,
      |                     ^~~~~~~~~~~~~
../drivers/gpu/drm/bridge/it6263.c:879:19: warning: assignment to ‘struct i2c_client *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  879 |  it6263->lvds_i2c = i2c_new_dummy(client->adapter,

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>