MGS-6835 [#ccc] fix build error of incompatible-pointer-types
commit fd3861c1434138db30083c57c6308382669aab07 from
https://github.com/nxp-imx/linux-imx.git

Fix build error when use imx_v6_v7 defconfig or enable CONFIG_PROVE_LOCKING.

drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel.c: In function ‘gckKERNEL_Construct’:
./drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_mutex.h:74:73: error: passing argument 3 of ‘gckOS_Allocate’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   74 |     gceSTATUS _status = gckOS_Allocate(Os, gcmSIZEOF(struct key_mutex), &key_mut); \
      |                                                                         ^~~~~~~~
      |                                                                         |
      |                                                                         struct key_mutex **
./drivers/mxc/gpu-viv/hal/kernel/inc/gc_hal_base.h:4427:18: note: in definition of macro ‘_gcmkONERROR’
 4427 |         status = func; \
      |                  ^~~~
drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel.c:584:9: note: in expansion of macro ‘gcmkONERROR’
  584 |         gcmkONERROR(gckOS_CreateMutex(Os, &kernel->db->dbMutex));
      |         ^~~~~~~~~~~
drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel.c:584:21: note: in expansion of macro ‘gckOS_CreateMutex’
  584 |         gcmkONERROR(gckOS_CreateMutex(Os, &kernel->db->dbMutex));
      |                     ^~~~~~~~~~~~~~~~~
In file included from drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_precomp.h:59,
                 from drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel.c:56:
./drivers/mxc/gpu-viv/hal/kernel/inc/gc_hal.h:293:22: note: expected ‘void **’ but argument is of type ‘struct key_mutex **’
  293 |     OUT gctPOINTER * Memory
      |         ~~~~~~~~~~~~~^~~~~~

Signed-off-by: yuan.tian <yuan.tian@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>