octeontx2-pf: Drop the dangling bypass_queue_check label
The codes which reference to bypass_queue_check label have been
removed by the merge commit fef27b087273 ("Merge branch
'v5.15/standard/base' into v5.15/standard/cn-sdkv5.15/octeon"), so we
also need to drop this dangling label in order to fix the build error
like below:
  drivers/net/ethernet/marvell/octeontx2/nic/otx2_flows.c: In function ‘otx2_add_flow’:
  drivers/net/ethernet/marvell/octeontx2/nic/otx2_flows.c:1187:1: error: label ‘bypass_queue_check’ defined but
   not used [-Werror=unused-label]
   1187 | bypass_queue_check:
        | ^~~~~~~~~~~~~~~~~~

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>