ARM: axxia: Fix support for kernel 5.10
commit c58df943def4c6de47c3f41eddb296df91ffabef from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

arch/arm/mach-axxia/axxia-gic.c:1424:2: error: implicit declaration
of function 'set_smp_cross_call' [-Werror=implicit-function-declaration]

arch/arm/mach-axxia/timers.c:221:2: error: implicit declaration of
function 'setup_irq'; did you mean 'setup_arch'?

arch/arm/mach-axxia/ddr_retention.c:317:6: error: passing argument 4
of 'proc_create' from incompatible pointer type

arch/arm/mach-axxia/ssp-gpio.c:66:15: error: implicit declaration of
function 'devm_ioremap_nocache'; did you mean 'devm_ioremap_release'?

arch/arm/mach-axxia/axxia.c:163:2: error: implicit declaration of
function 'set_dma_ops' [-Werror=implicit-function-declaration]

arch/arm/mach-axxia/axxia.c:163:20: error: 'arm_coherent_dma_ops'
undeclared (first use in this function

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>