LF-8222 dma: pxp: fix build error for pxp_device
commit 60bb62a13f7c3ea10a500e01e79dbe2abdb143e3 from
https://github.com/nxp-imx/linux-imx.git

../drivers/dma/pxp/pxp_device.c: In function 'pxp_dmabuf_ops_map':
../drivers/dma/pxp/pxp_device.c:666:40: error: 'struct dma_buf' has no member named 'lock'
  666 | struct mutex *lock = &db_attach->dmabuf->lock;
      |                                        ^~
../drivers/dma/pxp/pxp_device.c:666:15: warning: unused variable 'lock' [-Wunused-variable]
  666 | struct mutex *lock = &db_attach->dmabuf->lock;
      |               ^~~~

Remove internal dma-buf lock as it's removed in new framework and dma-buf reservation
is guaranteed to be locked by importers during the mapping operations.

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Reviewed-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>