arm: merge fixup for duplicate TIF_NOTIFY_SIGNAL and other TIF_*
This linux-stable backport:

  commit 855edc4ec64c197427e492c029dbf3230cc5f94c
  Author: Jens Axboe <axboe@kernel.dk>
  Date:   Wed Jan 4 07:48:37 2023 -0700

    ARM: renumber bits related to _TIF_WORK_MASK

    commit 191f8453fc99a537ea78b727acea739782378b0d upstream.

conflicts with the preempt-lazy patches from the -rt folks, resulting
in some post merge duplicates and compile failures like:

  arch/arm/include/asm/thread_info.h:141: error: "TIF_NOTIFY_SIGNAL" redefined [-Werror]

Ideally I would have copied the thread_info directly from the v5.15-rt
branch of linux-stable-rt[1] so that we'd stay exactly aligned with -rt
upstream for when/if we integrate future updates from the preempt-rt
people, but they haven't yet integrated the v5.15.87 with the offending
change yet.

[1] git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>