MLK-21876-10 gpu: drm: dpu: fix headfile reference issue (part 1)
commit 3611a14d5010762360e4f842208aabceb47c99f7 from
https://github.com/nxp-imx/linux-imx

../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>