arm: imx: Fix a build error undefined reference to `imx_smp_ops'
Due to imx7 compilation depends on some imx6 code,
so when imx6 config is not enabled, we will encounter
undefined reference to `imx_smp_ops', so include the
compilation of platsmp.c to imx7d.

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>