MGS-7214: gpu: imx: import DMA_BUF module namespace
commit cf3286dfb454984e2c5e0bd5a947f1772ca65973 from
https://github.com/nxp-imx/linux-imx.git

Build breaks when compiled as module, as follows:

MODPOST Module.symvers
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_attach
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_map_attachment
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_unmap_attachment
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_get
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_put
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_detach
 from namespace DMA_BUF, but does not import it.

Fixes: commit 5b8ce4a9037 ("MGS-7214: gpu: imx: dpu-blit: add generic dma-buf cache coherency management")
Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>
Reviewed-by: Xianzhong Li <xianzhong.li@nxp.com>
Reviewed-by: Guangliu Ding <guangliu.ding@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>