arm64: cpu_errata: fix unpaired brances
commit 3f42e5879d35(Merge branch 'v5.15/standard/base' into v5.15/standard/cn-sdkv5.4/octeon)
introduces unpaired brances, will cause build issue below, complete brace to fix this.

arch/arm64/kernel/cpu_errata.c:766:17: error: field name not in record or union initializer
   766 |                 .desc = "ARM erratum 2457168",
       |                 ^
arch/arm64/kernel/cpu_errata.c:766:17: note: (near initialization for 'arm64_errata[24].match_list')
arch/arm64/kernel/cpu_errata.c:766:25: error: initialization of 'const struct arm64_cpu_capabilities *' from incompatible pointer type 'char *' [-Werror=incompatible-pointer-types]
   766 |                 .desc = "ARM erratum 2457168",
       |                         ^~~~~~~~~~~~~~~~~~~~~
arch/arm64/kernel/cpu_errata.c:766:25: note: (near initialization for 'arm64_errata[24].match_list')
arch/arm64/kernel/cpu_errata.c:767:17: error: field name not in record or union initializer
   767 |                 .capability = ARM64_WORKAROUND_2457168,
       |                 ^

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>