LF-6810-01: media: parallel: fix build error due to API renamed
commit 9808fdda6b9578dd3af1fba561ae5f8ce6f92fa9 from
https://github.com/nxp-imx/linux-imx.git

Fix parallel driver build error due to API renamed in bellow commit:
drivers/staging/media/imx/imx8-parallel-csi.c:427:46:
error: implicit declaration of function ‘media_entity_remote_pad’; did you mean ‘media_entity_remove_links’? [-Werror=implicit-function-declaration]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
 media_pad_remote_pad_first())

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <Robby.Cai@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>