usb: gadget: udc-xilinx: fix compilation error
commit b3c78cec73db02c61a8feef3c5d21c3c3776dc7e from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

This patch fixed below complation error for zynq platform.
Replaced __memcpy_toio method with memcpy_toioto support both
platform zynq and zu+.

Error: implicit declaration of function '__memcpy_toio

Signed-off-by: Piyush Mehta <piyush.mehta@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>