net: octeontx2: nic: fix compile error caused by redefinition of otx2_nix_cq_op_status()
commit ec0db81883b4(octeontx2-pf: Use hardware register for CQE count)
introduced duplicate function definition 'otx2_nix_cq_op_status', this
function already available in SDK11's patches, so delete one to solve
the following compiling issue.

drivers/net/ethernet/marvell/octeontx2/nic/otx2_txrx.c:57:12: error: redefinition of 'otx2_nix_cq_op_status'
    57 | static int otx2_nix_cq_op_status(struct otx2_nic *pfvf,
       |            ^~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/marvell/octeontx2/nic/otx2_txrx.c:28:19: note: previous definition of 'otx2_nix_cq_op_status' with type 'int(struct otx2_nic *, struct otx2_cq_queue *)'
    28 | static inline int otx2_nix_cq_op_status(struct otx2_nic *pfvf,
       |                   ^~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>