LF-1162-3: clk: imx: imx8mm: add back required clk.h headfile
commit 58cf8f720c36c61ccc61e0a57bc3c0a2c4b49c42 from
https://source.codeaurora.org/external/imx/linux-imx

Otherwise meet below build break:
../drivers/clk/imx/clk-imx8mm.c: In function ‘imx_clk_init_on’:
../drivers/clk/imx/clk-imx8mm.c:313:9: error: implicit declaration of function ‘clk_prepare_enable’ [-Werror=implicit-function-declaration]
  313 |   ret = clk_prepare_enable(clks[array[i]]->clk);
      |         ^~~~~~~~~~~~~~~~~~
  AR      drivers/clk/mvebu/built-in.a

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>