LF-6810-04: media: isi cap: fix build error due to API renamed
commit 8ce07c5fccca7575b362d48fb4003b9be1b9e844 from
https://github.com/nxp-imx/linux-imx

drivers/staging/media/imx/imx8-isi-cap.c:602:46:
error: implicit declaration of function ‘media_entity_remote_pad’; did you mean ‘media_entity_remove_links’? [-Werror=implicit-function-declaration]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
 media_pad_remote_pad_first())

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <Robby.Cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>