arm64: dts: imx8mp: Restore pgc_mlmix back
The stable commit 0150dbc01d26 ("arm64: dts: imx8mp: Fix pgc_mlmix
location") shuffled the pgc_mlmix device nodel. However, pgc_mlmix was
missed due to the merge conflicts in commit 793df66c1def ("Merge branch
'v6.6/standard/base' into v6.6/standard/nxp-sdk-6.6/nxp-soc"). Restore
it back to fix below build errors:
  Error: arch/arm64/boot/dts/freescale/imx8mp-evk.dts:12.1-2 syntax error FATAL ERROR: Unable to parse input tree
  make[3]: *** [scripts/Makefile.lib:423: arch/arm64/boot/dts/freescale/imx8mp-evk.dtb] Error 1
  make[2]: *** [scripts/Makefile.build:480: arch/arm64/boot/dts/freescale] Error 2
  make[2]: *** Waiting for unfinished jobs....

Also add a missing '}' for pgc_gpu2d.

Reported-by: leimaohui <leimaohui@fujitsu.com>
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>