arch: arm64: change the formal parameters to fit the new kernel data structure
After commit 46ddfb9d1e46 (arm64: Treat ESR_ELx as a 64-bit register),
ESR_ELx is defined as 64-bit register. We need to adapt this change for
marvell erratum 38891 to avoid the following compilation problems.

arch/arm64/kernel/traps.c:702:28: error: initialization of 'void (*)(long unsigned int,  struct pt_regs *)' from incompatible pointer type 'void (*)(unsigned int,  struct pt_regs *)' [-Werror=incompatible-pointer-types]
  702 |                 .handler = user_cache_maint_handler,
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~
arch/arm64/kernel/traps.c:702:28: note: (near initialization for 'sys64_hooks[0].handler')
arch/arm64/kernel/traps.c:708:28: error: initialization of 'void (*)(long unsigned int,  struct pt_regs *)' from incompatible pointer type 'void (*)(unsigned int,  struct pt_regs *)' [-Werror=incompatible-pointer-types]
  708 |                 .handler = ctr_read_handler,
      |                            ^~~~~~~~~~~~~~~~

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>