MLK-13470 mfd: max17135: export symbols to fix build error as a module
commit 0fff1a169dd337f0d51f93994a468da8cd56fd58 from
https://source.codeaurora.org/external/imx/linux-imx

export symbols to fix build error as a module:

ERROR: "max17135_reg_read" [drivers/hwmon/max17135-hwmon.ko] undefined!

Signed-off-by: Julien Olivain <julien.olivain@nxp.com>
Acked-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>