LF-665-4 input: mma8450: fix build break
commit 30c78dc3b9a703b075901398d9e4a5ace5707b2c from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/input/misc/mma8450.c: In function 'mma8450_probe':
../drivers/input/misc/mma8450.c:156:6: error: redeclaration of 'err' with no linkage
  int err, client_id;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>