dmaengine: Fix Axxia DMA32 driver for kernel 5.10
commit 358b0e6a02f4fb6f28ab5646b9a00c7c10dffae2 from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

drivers/dma/axxia-dma32.c:803:19: error: implicit declaration of
function 'devm_ioremap_nocache'; did you mean 'devm_ioremap_resource'?

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>