ARM: mach-imx: conditionally disable some functions from busfreq-imx
commit daa0282773d3b89cac8adbec35bcdf9df25a566b from
https://github.com/nxp-imx/linux-imx.git

In case CONFIG_HAVE_IMX_BUSFREQ is not set, there are mocks for some
functions from busfreq-imx declared. It fails kernel building with an
error [1].
Disable duplicated functions from busfreq-imx fixes this issue.

[1]
...
| arch/arm/mach-imx/busfreq-imx.c:821:6: error: redefinition of 'request_bus_freq'
|   821 | void request_bus_freq(enum bus_freq_mode mode)
|       |      ^~~~~~~~~~~~~~~~
| In file included from arch/arm/mach-imx/busfreq-imx.c:23:
| include/linux/busfreq-imx.h:58:20: note: previous definition of 'request_bus_freq' was here
|    58 | static inline void request_bus_freq(enum bus_freq_mode mode)
|       |                    ^~~~~~~~~~~~~~~~
...

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>
Acked-by: Jason Liu <jason.hui.liu@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>