media: imx-jpeg: Reapply the missing codes in mxc_jpeg_probe()
Due to the merge conflicts, part of the changes in the stable commit
09fc82a6a7a8 ("media: imx-jpeg: Apply clk_bulk api instead of operating
specific clk") was missed. Reapply these codes to fix the following
build failure.
  drivers/media/platform/imx-jpeg/mxc-jpeg.c: In function 'mxc_jpeg_probe':
  drivers/media/platform/imx-jpeg/mxc-jpeg.c:2112:13: error: 'struct mxc_jpeg_dev' has no member named 'clk_ipg'

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>