v4l: xilinx: events: Fix the uapi header license
commit 3e988444b9c392dc2109a3a76c1928d63a4914d3 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>