MLK-21876-10 gpu: drm: lcdif: fix headfile reference issue
commit a8924bcddaf39cdbd6cf23a4674f2b207810a001 from
https://github.com/nxp-imx/linux-imx.git

  CC      drivers/gpu/drm/imx/lcdif/lcdif-crtc.o
../drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:26:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>