MLK-21985-8 media: isi: fix build for next 20190607 upgrade
commit 4a75abf4281d682b2ba439dda64354f07f5f81bb from
https://github.com/nxp-imx/linux-imx.git

API change due to commit:
7e98b7b542a4 ("media: v4l2: Get rid of ->vidioc_enum_fmt_vid_{cap, out}_mplane")

../drivers/staging/media/imx/imx8-isi-cap.c:1211:2: error: unknown field ‘vidioc_enum_fmt_vid_cap_mplane’ specified in initializer
  .vidioc_enum_fmt_vid_cap_mplane = mxc_isi_cap_enum_fmt_mplane,

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>