pcie: aer: Fix build error of unpaired braces
Commit 8b2ad28597b0 (Merge branch 'v5.15/standard/base' into v5.15/
standard/cn-sdkv5.4/octeon) introduced unpaired braces when dealing
with conflicts in file drivers/pci/pcie/portdrv_core.c. This causes
build issue below, fix by remove unnecessary brance.

drivers/pci/pcie/portdrv_core.c: In function 'get_port_device_capability':
drivers/pci/pcie/portdrv_core.c:279:12: error: invalid storage class for function 'pcie_device_init'
  279 | static int pcie_device_init(struct pci_dev *pdev, int service, int irq)
      |            ^~~~~~~~~~~~~~~~

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>