LF-11107 irq: gic-v3: fix build break for Cockpit
commit 6359a1321cbbf9e8b5fea54177aa37801114f322 from
https://github.com/nxp-imx/linux-imx.git

After enabling CONFIG_GIC_GENTLE_CONFIG, there will be a build
break due to the GIC affinity helper API gic_mpidr_to_affinity()
we used was removed since the upstream commit
3c65cbb7c5eb ("irqchip/gic-v3: Improve affinity helper")

Update the code to use the new one accordingly to fix the
build break.

Error Log:
aarch64-poky-linux-ld: Unexpected GOT/PLT entries detected!
aarch64-poky-linux-ld: Unexpected run-time procedure linkages detected!
aarch64-poky-linux-ld: drivers/irqchip/irq-gic-v3.o: in function `gic_set_type':
drivers/irqchip/irq-gic-v3.c:684: undefined reference to `gic_mpidr_to_affinity'
make[3]: *** [../scripts/Makefile.vmlinux:37: vmlinux] Error 1

Cc: Nitin Garg <nitin.garg_3@nxp.com>
Reviewed-by: Jacky Bai <ping.bai@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>