MGS-5612 [#IMX-2018] fix weston build error
commit 0023bbcc5324d3288e42ead610a0bb46590851c2 from
https://github.com/nxp-imx/linux-imx.git

fix weston build error such as:

/opt/fsl-imx-internal-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr/include/HAL/shared/gc_hal_types_shared.h:17:10:
fatal error: gc_hal_version.h: No such file or directory
       17 | #include "gc_hal_version.h"
          |          ^~~~~~~~~~~~~~~~~~
          compilation terminated.

Signed-off-by: Minjie Zhuang <minjie.zhuang@nxp.com>
Signed-off-by: Yong Gan <yong.gan@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>