cifs: Fix the calling of smb_version_operations::calc_smb_size()
The c4fa05422d87 ("smb: client: fix potential OOB in
smb2_dump_detail()") was backported from upstream. But the definition
of smb_version_operations::calc_smb_size() is different between latest
upstream and v5.15. So the calling of calc_smb_size() causes below
error:
  fs/cifs/smb2ops.c:378:33: error: too few arguments to function ‘server->ops->calc_smb_size’
    378 |                                 server->ops->calc_smb_size(buf));

Add the missed parameter to fix this issue.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>