staging: fsl_qbman: include new header file linux/dma-mapping.h
commit 9b95aa7e3d7ac1c50b310e4f6df1d84af22958a8 from
https://source.codeaurora.org/external/imx/linux-imx

New headfile introduced from:
0a0f0d8be76d ("dma-mapping: split <linux/dma-mapping.h>")

Including it to fix the build issue below:

drivers/staging/fsl_qbman/qman_high.c: In function ‘qman_create_portal’:
drivers/staging/fsl_qbman/qman_high.c:687:2: error: implicit declaration of function ‘arch_setup_dma_ops’; did you mean ‘arch_setup_new_exec’? [-Werror=implicit-function-declaration]
  arch_setup_dma_ops(&portal->pdev->dev, 0, 0, NULL, true);
  ^~~~~~~~~~~~~~~~~~
  arch_setup_new_exec

Signed-off-by: Li Yang <leoyang.li@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>