Revert "ARM: 9113/1: uaccess: remove set_fs() implementation"
commit  9c54cf1f82ccb18b8178400d27f09524bafaccfe from
https://github.com/nxp-imx/linux-imx lf-6.1.y

This reverts commit 8ac6f5d7f84bf362e67591708bcb9788cdc42c50.

i.MX still uses it.

../drivers/media/platform/mxc/capture/mxc_v4l2_capture.c: In function ‘verify_preview’:
../drivers/media/platform/mxc/capture/mxc_v4l2_capture.c:549:14: error: implicit declaration of function ‘get_fs’; did you mean ‘sget_fc’? []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration]8;;]
  549 |     old_fs = get_fs();
      |              ^~~~~~
      |              sget_fc

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>