crypto: octeontx: fix header search path
commit 5200bd7ec72ac2ed09a39db808076add60744b71 from
git@git.assembla.com:cavium/WindRiver.linux.git

Instead of adding header search path which starts at current Makefile
and goes backward and then forward we may simply start at the root of
kernel source tree and descend to proper directory.

So apart from readability this also resolves compilation issue.

In file included from
../drivers/crypto/marvell/octeontx/otx_cptpf_mbox.c:12:
../drivers/crypto/marvell/octeontx/otx_cptpf.h:18:10: fatal error:
octeontx.h: No such file or directory
   18 | #include "octeontx.h"
         |          ^~~~~~~~~~~~
	 compilation terminated.

Signed-off-by: Tomasz Duszynski <tduszynski@marvell.com>
Change-Id: Ib772fa766f0c30c7394baae48d7e204d25362d61
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/76314
Reviewed-by: Jerin Jacob Kollanukkaran <jerinj@marvell.com>
Reviewed-by: Harman Kalra <hkalra@marvell.com>
Reviewed-by: Srujana Challa <schalla@marvell.com>
Tested-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
(cherry picked from commit 3edb51031de347fece3f09f1f71ac5a551d07737)
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/76374
Reviewed-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>