LF-2567-4 arm: imx: fix rpmsg build failure with multi_v7_defconfig
commit 3706f08aa03d4504f618061d80332ff3ea359a63 from
https://source.codeaurora.org/external/imx/linux-imx

HAVE_IMX_RPMSG depends on IMX_MBOX which should also be selected.
otherwise we meet below build errors:

arm-poky-linux-gnueabi-ld: arch/arm/mach-imx/pm-rpmsg.o: in function `pm_heartbeat_probe':
pm-rpmsg.c:(.text+0x14): undefined reference to `__register_rpmsg_driver'
arm-poky-linux-gnueabi-ld: arch/arm/mach-imx/pm-rpmsg.o: in function `pm_send_message.constprop.0':
pm-rpmsg.c:(.text+0x94): undefined reference to `rpmsg_send'

It was caused by RPMSG was not correctly selected by HAVE_IMX_RPMSG
due to unmet dependency.

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>