samples: pfsm: add CC_CAN_LINK dependency
commit b5e4e65a65deedefb7fdf655edfdee8157e3ae7d from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

When no libc for the target architecture is available, cross-compiling
the same cannot work:

samples/pfsm/pfsm-wakeup.c:12:10: fatal error: fcntl.h: No such file or directory

Fixes: 9e66fb5244953 ("samples: Add userspace example for TI TPS6594 PFSM")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Vignesh Raghavendra <vigneshr@ti.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>