crypto: octeontx2: supplement function is_any_alg_used() according to SDK
Compared with SDK11, upstream commit 6f03f0e8b6c8 (crypto: octeontx2 -
register with linux crypto framework) missed function is_any_alg_used(),
after commit 2b94fd0aead0(crypto: octeontx2: sync with upstream driver),
we catched compile error below, add missing function accroding to SDK11
to fix this.

drivers/crypto/marvell/octeontx2/otx2_cptvf_algs.c: In function 'otx2_cpt_crypto_exit':
drivers/crypto/marvell/octeontx2/otx2_cptvf_algs.c:1749:14: error: implicit declaration of function 'is_any_alg_used' [-Werror=implicit-function-declaration]
 1749 |             !is_any_alg_used()) {
      |              ^~~~~~~~~~~~~~~

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>