clk: clk-xlnx-clock-wizard: fix 64bit division on 32bit archs
commit b95dcd3afd2c09cfc021dd4748b61918352afce1 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.1

Use the proper APIs to do 64bit division on 32bit architectures.
Otherwise we get:

"undefined reference to `__aeabi_uldivmod'"

Fixes: bf7387ee9a75c ("clocking-wizard: Support higher frequency accuracy")
Signed-off-by: Nuno Sa <nuno.sa@analog.com>
Reviewed-by: Shubhrajyoti Datta <shubhrajyoti.datta@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>