MA-20197-3 uapi: mxc_v4l2: use __u32 instead of uint32_t
commit 969d8479b9b24620ef295fe2de3e9d06c5ddf872 from
https://github.com/nxp-imx/linux-imx.git

Enable CONFIG_UAPI_HEADER_TEST turns on the following build issue:
./usr/include/linux/mxc_v4l2.h:52:2: error: unknown type name 'uint32_t'
        uint32_t u_offset;
        ^
./usr/include/linux/mxc_v4l2.h:53:2: error: unknown type name 'uint32_t'
        uint32_t v_offset;
        ^
./usr/include/linux/mxc_v4l2.h:57:2: error: unknown type name '__u32'
        __u32                   type;   /* enum v4l2_buf_type */
        ^

To fix it, use __u32 instead of uint32_t and include linux/types.h.

Change-Id: I7cda0e0bf7e712a0419bbab1723f597283c56ad9
Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>