LF-2444: soc: imx: secvio: Add dependency on IMX_SCU
commit c6eca01425294eb9ae8b3dced20d43684168e30a from
https://github.com/nxp-imx/linux-imx.git

When configuring the kernel to not support iMX, eg:
 - make defconfig
 - make lsdk.config
 - CONFIG_ARCH_MXC=n

The build fails:
aarch64-fsl-linux-ld: drivers/soc/imx/secvio/imx-secvio-sc.o:
	in function `int_imx_secvio_sc_disable_irq':
linux-nxp/drivers/soc/imx/secvio/imx-secvio-sc.c:385:
	undefined reference to `imx_scu_irq_group_enable'
aarch64-fsl-linux-ld: drivers/soc/imx/secvio/imx-secvio-sc.o:
	in function `int_imx_secvio_sc_enable_irq':
linux-nxp/drivers/soc/imx/secvio/imx-secvio-sc.c:343:
	undefined reference to `imx_scu_irq_group_enable'
Makefile:1173: recipe for target 'vmlinux' failed

It happens because secvio module requires imx-scu-irq disabled
with CONFIG_ARCH_MXC=n.

This patch modify the Kconfig for the module to add a dependency
on IMX_SCU symbol.

Fixes: 262bd66fafcb (SSI-87: soc: imx: secvio: Add support for SNVS secvio and tamper via SCFW)
Signed-off-by: Franck LENORMAND <franck.lenormand@nxp.com>
Reviewed-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>