lttng: Move nmi_return pv_ops out of lguest_pages
Fix below compile error when lguest is enabled:
error: invalid use of undefined type 'struct pv_cpu_ops'

And, move both x86_32 and x86_64 nmi_return pv_ops to common
asm-offsets.c since they have the same definition.

Signed-off-by: Yang Shi <yang.shi@windriver.com>