LF-1011-26 arm: imx: pm-imx7: fix build break when calling of_flat_dt_match
commit f3b3d5783d2fac4a8aaa4f0706a8512bead00bff from
https://github.com/nxp-imx/linux-imx

Old API was hiddened from user.

../arch/arm/mach-imx/pm-imx7.c: In function ‘imx7_dt_find_lpsram’:
../arch/arm/mach-imx/pm-imx7.c:891:6: error: implicit declaration of function ‘of_flat_dt_match’ [-Werror=implicit-function-declaration]
  891 |  if (of_flat_dt_match(node, low_power_ocram_match)) {
      |      ^~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>