LF-1162-5: clk: imx: imx8mm: add back required clk.h headfile
commit afcaa8c33ba67e871c9f846cc152b2a5297535f0 from
https://github.com/nxp-imx/linux-imx

Otherwise meet below build break:
../drivers/clk/imx/clk-imx8mn.c: In function ‘imx_clk_init_on’:
../drivers/clk/imx/clk-imx8mn.c:306:9: error: implicit declaration of function ‘clk_prepare_enable’ [-Werror=implicit-function-declaration]
  306 |   ret = clk_prepare_enable(clks[array[i]]->clk);
      |         ^~~~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>