MA-20005-12 hantro_vc8000e: Fix build error exposed by -Wunused-variable
commit b869dfb049b376decb9ecdf86d4dc1256eb40b18 from
https://github.com/nxp-imx/linux-imx.git

Fix below two build errors:
drivers/mxc/hantro_vc8000e/hx280enc_vc8000e.c:149:30: error: unused variable 'asic_status' [-Werror,-Wunused-variable]
static volatile unsigned int asic_status;
                             ^

drivers/mxc/hantro_vc8000e/hx280enc_vc8000e.c:702:13: error: unused function 'hantroenc_ioctl32' [-Werror,-Wunused-function]
static long hantroenc_ioctl32(struct file *filp, unsigned int cmd, unsigned long arg)
            ^

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Shijie Qin <shijie.qin@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>