LF-3326-1 drm/imx: lcdif: fix several build errors during rebase
commit d7799db0cc78fa53c7f51a75da06bc055ee18008 from
https://github.com/nxp-imx/linux-imx.git

Due to the commit eca22edb37d2 (drm: Pass the full state to
connectors atomic functions), below build errors happened:

drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:204:18: error: initialization of ‘int (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘int (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  204 |  .atomic_check = lcdif_crtc_atomic_check,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:204:18: note: (near initialization for ‘lcdif_helper_funcs.atomic_check’)
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:205:18: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  205 |  .atomic_begin = lcdif_crtc_atomic_begin,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:205:18: note: (near initialization for ‘lcdif_helper_funcs.atomic_begin’)
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:206:18: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  206 |  .atomic_flush = lcdif_crtc_atomic_flush,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:206:18: note: (near initialization for ‘lcdif_helper_funcs.atomic_flush’)
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:207:19: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  207 |  .atomic_enable = lcdif_crtc_atomic_enable,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:207:19: note: (near initialization for ‘lcdif_helper_funcs.atomic_enable’)
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:208:20: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  208 |  .atomic_disable = lcdif_crtc_atomic_disable,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:208:20: note: (near initialization for ‘lcdif_helper_funcs.atomic_disable’)

Signed-off-by: Fancy Fang <chen.fang@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>