LF-4575-2 media: v4l2-async: fix build error after revert patch for V4L2_ASYNC_MATCH_DEVNAME
commit 0678ad28981547710dbc01f7494dc0ec7b68f957 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/media/v4l2-core/v4l2-async.c: In function 'v4l2_async_notifier_add_devname_subdev':
../drivers/media/v4l2-core/v4l2-async.c:736:8: error: implicit declaration of function 'v4l2_async_notifier_add_subdev'; did you mean 'v4l2_async_notifier_add_i2c_subdev'? [-Werror=implicit-function-declaration]
  736 |  ret = v4l2_async_notifier_add_subdev(notifier, asd);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |        v4l2_async_notifier_add_i2c_subdev
cc1: some warnings being treated as errors
make[4]: *** [../scripts/Makefile.build:272: drivers/media/v4l2-core/v4l2-async.o] Error 1
make[3]: *** [../scripts/Makefile.build:536: drivers/media/v4l2-core] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [../scripts/Makefile.build:536: drivers/media] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/home/nxa14866/ProjectA/linux-nxp/Makefile:1996: drivers] Error 2
make: *** [Makefile:227: __sub-make] Error 2

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Reviewed-by: G.n. Zhou <guoniu.zhou@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>