bpftool: Fix undefined bpf macro for unix socket
42b2eec2e503 ("bpftool: Query only cgroup-related attach types") is for the
latest mainline, in which the following marcos were introduced since v6.7
while we're at v6.6. Since 42b2eec2e503 will not be back-ported to uptream
stable tree, let's remove the marcos.

| cgroup.c:33:9: error: 'BPF_CGROUP_UNIX_CONNECT' undeclared here
(not in a function); did you mean 'BPF_CGROUP_INET6_CONNECT'?
|    33 |         BPF_CGROUP_UNIX_CONNECT,
|       |         ^~~~~~~~~~~~~~~~~~~~~~~
|       |         BPF_CGROUP_INET6_CONNECT
| cgroup.c:36:9: error: 'BPF_CGROUP_UNIX_GETPEERNAME' undeclared here
(not in a function); did you mean 'BPF_CGROUP_INET6_GETPEERNAME'?
|    36 |         BPF_CGROUP_UNIX_GETPEERNAME,
|       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |         BPF_CGROUP_INET6_GETPEERNAME
| cgroup.c:39:9: error: 'BPF_CGROUP_UNIX_GETSOCKNAME' undeclared here
(not in a function); did you mean 'BPF_CGROUP_INET6_GETSOCKNAME'?
|    39 |         BPF_CGROUP_UNIX_GETSOCKNAME,
|       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |         BPF_CGROUP_INET6_GETSOCKNAME
| cgroup.c:42:9: error: 'BPF_CGROUP_UNIX_SENDMSG' undeclared here
(not in a function); did you mean 'BPF_CGROUP_UDP6_SENDMSG'?
|    42 |         BPF_CGROUP_UNIX_SENDMSG,
|       |         ^~~~~~~~~~~~~~~~~~~~~~~
|       |         BPF_CGROUP_UDP6_SENDMSG
| cgroup.c:45:9: error: 'BPF_CGROUP_UNIX_RECVMSG' undeclared here
(not in a function); did you mean 'BPF_CGROUP_UDP6_RECVMSG'?
|    45 |         BPF_CGROUP_UNIX_RECVMSG,
|       |         ^~~~~~~~~~~~~~~~~~~~~~~
|       |         BPF_CGROUP_UDP6_RECVMSG

Fixes: 42b2eec2e503 ("bpftool: Query only cgroup-related attach types")
Signed-off-by: He Zhe <zhe.he@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>