drm/tidss: fix uninitialized variable
commit d0d1c85c6a0265054fae482713a8d17d2c5839ef from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

When we build with android build fail on :
 error: variable 'mask' is used uninitialized whenever 'if' condition is
 false

To fix this initialize mask variable.

Fixes: 93022077f0f5 ("TI: drm/tidss: Add OLDI bridge support")
Change-Id: If2ae28b61fe6c0e15bb7a27f2098ed1dd6c2c2e4
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>
Reviewed-by: Aradhya Bhatia <a-bhatia1@ti.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>