gianfar: fix compile error
Below compile error happens when building gianfar:
linux/drivers/net/gianfar.c: In function 'get_cpu_number':
linux/drivers/net/gianfar.c:1159: warning: assignment from incompatible pointer type
linux/drivers/net/gianfar.c:1178: error: dereferencing pointer to incomplete type
linux/drivers/net/gianfar.c:1182: error: dereferencing pointer to incomplete type
linux/drivers/net/gianfar.c: In function 'gfar_probe':
drivers/net/gianfar.c:1230: warning: unused variable 'j'
drivers/net/gianfar.c: In function 'gfar_tx_checksum':
drivers/net/gianfar.c:2687: error: 'IP_MF' undeclared (first use in this function)
drivers/net/gianfar.c:2687: error: (Each undeclared identifier is reported only once
drivers/net/gianfar.c:2687: error: for each function it appears in.)
drivers/net/gianfar.c:2687: error: 'IP_OFFSET' undeclared (first use in this function)
drivers/net/gianfar.c: In function 'gfar_clean_tx_ring':
drivers/net/gianfar.c:3462: error: 'nr_txbds' undeclared (first use in this function)

Fix this problem by:
1. add header file net/ip.h.
2. remove useless variable 'j'.
3. add the missed chang by replace nr_txbds with frags.

Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>