Revert "ARM: 9113/1: uaccess: remove set_fs() implementation"
commit ee69377c0fb428a2319ca071bbdbbddbb756cd02 from
https://source.codeaurora.org/external/imx/linux-imx

This reverts commit 8ac6f5d7f84bf362e67591708bcb9788cdc42c50.

i.MX still uses it.

../drivers/media/platform/mxc/capture/mxc_v4l2_capture.c: In function ‘verify_preview’:
../drivers/media/platform/mxc/capture/mxc_v4l2_capture.c:549:14: error: implicit declaration of function ‘get_fs’; did you mean ‘sget_fc’? []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration]8;;]
  549 |     old_fs = get_fs();
      |              ^~~~~~
      |              sget_fc

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>