MLK-23547: ASoC: SOF: Use machine_drv_name on OF platforms
commit 3c1577fad1d1bdf6bd9b555263dbcc5bb0a852e7 from
https://github.com/nxp-imx/linux-imx.git

On OF platforms information about machine driver is stored
in sof_pdata->machine_drv_name.

Without this SOF probe fails with:
error: no matching ASoC machine driver found - aborting probe

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>