tracing/ftrace: Fixes the trace_clock_local() for the boards who use the jiffies based sched_clock()
This patch fixes the selftest failure of the irqsoff, preemptoff,
preemptirqsoff and wakeup tracers:

Testing tracer nop: PASSED
Testing tracer sched_switch: PASSED
Testing tracer function: PASSED
Testing tracer irqsoff: .. no entries found .. FAILED!
Testing tracer preemptoff: .. no entries found ..FAILED!
Testing tracer preemptirqsoff: .. no entries found ..FAILED!
Testing tracer wakeup: .. no entries found ..FAILED!
Testing tracer function_graph: PASSED

By default, Ftrace uses the jiffies based sched_clock() to get the
timestamp if there is no architecture specific one. but the resolution
of this default sched_clock() is very bad: only ~ms. which is useless
for the tracers, expecially for the above latency tracers(irqsoff,
preemptoff, preemptirqsoff), and even make the selftest of these tracers
fail:

To explain the cause, we only use irqsoff as an example.

In trace_selftest_startup_irqsoff(), we only sleep for 100us, so, the
delta of the timestamp gotten by sched_clock() is 0, then, in
check_critical_timing(), the report_latency() will return 0 for the
delta(0) is always smaller than tracing_thresh or equal to
tracing_max_latency. and then, there is no opportunity to do
update_max_tr_single(), then, no entry is the max_tr's buffer, the count
is 0, and selftest failure.

A quick fix is sleep for more than 10ms(in the HZ is 100) in
trace_selftest_startup_irqsoff() to ensure the data can be recorded in
the max_tr's buffer but this doesn't help to fix the useless timestamp
information of the tracers, so, a real fix is use a high resolution
trace_clock_local().

There is such a patch from http://patchwork.linux-mips.org/patch/1104/,
but that one is not suitable for SMP and it is R4K timer specific.

Another choice is the trace-clock-32-to-64 contributed by Lttng, it is
architecture independent and it has been considered for SMP. So, this
patch uses it.

BTW, the following building error on omap is fixed by adding the missing
<linux/percpu.h>.

Without this fix, there will be building errors:

In file included from arch/arm/include/asm/trace-clock.h:2,
                 from include/linux/trace-clock.h:14,
                 from kernel/trace/trace-clock-cyc2ns.c:14:
arch/arm/plat-omap/include/plat/trace-clock.h:71: error: expected declaration specifiers or '...' before 'pm_save_count'
arch/arm/plat-omap/include/plat/trace-clock.h:71: warning: data definition has no type or storage class
arch/arm/plat-omap/include/plat/trace-clock.h:71: warning: type defaults to 'int' in declaration of 'DECLARE_PER_CPU'
arch/arm/plat-omap/include/plat/trace-clock.h:77: error: expected declaration specifiers or '...' before 'fast_clock_ready'
arch/arm/plat-omap/include/plat/trace-clock.h:77: warning: data definition has no type or storage class
arch/arm/plat-omap/include/plat/trace-clock.h:77: warning: type defaults to 'int' in declaration of 'DECLARE_PER_CPU'
arch/arm/plat-omap/include/plat/trace-clock.h:77: error: conflicting types for 'DECLARE_PER_CPU'
arch/arm/plat-omap/include/plat/trace-clock.h:71: note: previous declaration of 'DECLARE_PER_CPU' was here
In file included from arch/arm/include/asm/trace-clock.h:2,
                 from include/linux/trace-clock.h:14,
                 from kernel/trace/trace-clock-cyc2ns.c:14:
arch/arm/plat-omap/include/plat/trace-clock.h: In function 'trace_clock_read64':
arch/arm/plat-omap/include/plat/trace-clock.h:130: error: implicit declaration of function 'per_cpu'
arch/arm/plat-omap/include/plat/trace-clock.h:130: error: 'pm_save_count' undeclared (first use in this function)
arch/arm/plat-omap/include/plat/trace-clock.h:130: error: (Each undeclared identifier is reported only once
arch/arm/plat-omap/include/plat/trace-clock.h:130: error: for each function it appears in.)
arch/arm/plat-omap/include/plat/trace-clock.h:130: error: implicit declaration of function 'smp_processor_id'
arch/arm/plat-omap/include/plat/trace-clock.h:130: error: lvalue required as unary '&' operand
remake[5]: *** [kernel/trace/trace-clock-cyc2ns.o] Error 1
remake[4]: *** [kernel/trace] Error 2
Makefile:895: *** [kernel] Error 2
remake[2]: *** [sub-make] Error 2
remake[1]: *** [linux.compile] Error 2
make: *** [linux.compile] Error 2

Notes:

   o check_res_of_trace_clock() must be finished before the register of
   latency tracers(device_initcall) to ensure the high resolution trace
   clocks are available for them.

   o we must ensure the low-level clocks have been initialized before
   our check_res_of_trace_clock(), so, we put them in early_initcall(),

   o we must release the trace clock explicitly when want to switch
   Ftrace to Lttng with the same kernel:
      $ echo nop > /path/to/debug/tracing/current_tracer

Signed-off-by: Wu Zhangjin <zhangjin.wu@windriver.com>