media: cadence: csi2rx: correct not defined label
Correct not defined label introduced by wrong merging and to fix below
building issue:

drivers/media/platform/cadence/cdns-csi2rx.c:339:17: error: label 'err_disable_sysclk' used but not defined
|   339 |                 goto err_disable_sysclk;
|       |                 ^~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>