LTTNG2: fix compilation issue for 64bit targets.
vsyscall_64.c calls _trace_clock_is_sync even if
CONFIG_HAVE_TRACE_CLOCK is not defined.  The result is:

linux/arch/x86/kernel/vsyscall_64.c:124: undefined reference to
`_trace_clock_is_sync'

cf: arch/x86/kernel/Makefile:
	obj-$(CONFIG_X86_64)	+= vsyscall_64.o
	....
	obj-$(CONFIG_HAVE_TRACE_CLOCK)	+= trace-clock.o

Added the appropriate ifdefs to make sure _trace_clock_is_sync is not
referenced.  This fix is only required for 64bit compilations.

Signed-off-by: Paul Barrette <paul.barrette@windriver.com>