MLK-21876-11 gpu: fix build for next-20190524 upgrade
commit c17cfe326131372ad47cad76b00f72ab45a38da0 from
https://source.codeaurora.org/external/imx/linux-imx

Failed on imx v6_v7 build.

../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:86:17: fatal error: dma.h: No such file or directory
 #include <dma.h>
                 ^
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>