ocf: OCF_CRYPTOSOFT depends on CRYPTO_HASH2
ERROR: "crypto_alloc_ahash" [crypto/ocf/cryptosoft.ko] undefined!
ERROR: "crypto_alloc_ablkcipher" [crypto/ocf/cryptosoft.ko] undefined!
ERROR: "crypto_ahash_digest" [crypto/ocf/cryptosoft.ko] undefined!
ERROR: "crypto_ahash_setkey" [crypto/ocf/cryptosoft.ko] undefined!

These are defined in crypto/ahash.c, which is enabled by CRYPTO_HASH2.

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>