LF-1011-33 media: capture: mxc_v4l2: remove using of ns_to_timeval
commit c0f7f3f922a514eb38f9cdf105e314449ce83163 from
https://source.codeaurora.org/external/imx/linux-imx

This API was removed.

../drivers/media/platform/mxc/capture/mxc_v4l2_capture.c: In function ‘camera_callback’:
../drivers/media/platform/mxc/capture/mxc_v4l2_capture.c:2563:4: error: implicit declaration of function ‘ns_to_timeval’; did you mean ‘ns_to_ktime’? [-Werror=implicit-function-declaration]
 2563 |    ns_to_timeval(ts.tv_sec * 1000000000ULL + ts.tv_nsec);
      |    ^~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>