media: platform: vxe-vxd: wrap hwctrl_dump_state() with debug macro
Wrap hwctrl_dump_state() with debug macro DEBUG_DECODER_DRIVER, to
fix below building issue:
drivers/media/platform/vxe-vxd/decoder/hw_control.c:775:13: error: 'hwctrl_dump_state'
defined but not used [-Werror=unused-function]
|   775 | static void hwctrl_dump_state(struct vxd_states *prev_state,
|       |             ^~~~~~~~~~~~~~~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>