misc: axxia: Fix OEM Handling for kernel 5.10
commit 0161116c6b6b360fa4caa1c692ebbf4ed45eea44 from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

drivers/misc/axxia-oem.c:582:4: error: passing argument 4 of
   'proc_create' from incompatible pointer type
   [-Werror=incompatible-pointer-types]

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>