net: update the AF_MAX value to the latest
commit c6f441a33dd (net/rpmsg: add support for new rpmsg sockets) adds
a new socket address AF_RPMSG, the AF_MAX should be incremented accordingly.

To avoid below building error:
net/core/sock.c:233:21: error: excess elements in array initializer [-Werror]
|   233 |         _sock_locks("sk_lock-")

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>