of: reserved_mem: switch to memblock_phys_alloc_range
commit aaaa01b3cca34d85625f29c5f45f1019ae44c6d3 from
https://source.codeaurora.org/external/imx/linux-imx

The memblock_find_in_range() API was changed to core private function since
commit 461ef12c4375 ("memblock: make memblock_find_in_range method private").

Change to new API memblock_phys_alloc_range to avoid build break.

    ../drivers/of/of_reserved_mem.c: In function ‘early_init_dt_alloc_reserved_memory_arch’:
    ../drivers/of/of_reserved_mem.c:56:11: error: implicit declaration of function ‘memblock_find_in_range’ [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration8;;]
       56 |    base = memblock_find_in_range(start, highmem_start,

Reviewed-by: Jason Liu <jason.hui.liu@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>