net: ethernet: Fix Intel Axxia NEMAC GigE driver for kernel 5.10
commit 877f53fbd81cf06d721ad95f681b0164891e218b from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

drivers/net/ethernet/intel/axxia/nemac.c:888:22: error: initialization
   of 'void (*)(struct net_device *, unsigned int)' from incompatible
   pointer type 'void (*)(struct net_device *)'
   [-Werror=incompatible-pointer-types]

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>