netdev/phy/icplus: Fix broken build since 10G phy support update
SDK commit a2e7e34 "Convert MDIO and PHY Lib drivers to support 10G"
broke mpc83xx_defconfig builds in the following manner:

drivers/net/phy/icplus.c: In function 'ip175c_config_init':
drivers/net/phy/icplus.c:45:3: error: too few arguments to function 'mdiobus_write'
include/linux/phy.h:139:5: note: declared here
drivers/net/phy/icplus.c:50:3: error: too few arguments to function 'mdiobus_read'
include/linux/phy.h:138:5: note: declared here
drivers/net/phy/icplus.c:56:3: error: too few arguments to function 'mdiobus_write'
include/linux/phy.h:139:5: note: declared here
drivers/net/phy/icplus.c:61:3: error: too few arguments to function 'mdiobus_write'
include/linux/phy.h:139:5: note: declared here
drivers/net/phy/icplus.c:68:10: error: too few arguments to function 'mdiobus_write'
include/linux/phy.h:139:5: note: declared here
drivers/net/phy/icplus.c:74:4: error: too few arguments to function 'mdiobus_read'
include/linux/phy.h:138:5: note: declared here

Fix it

Signed-off-by: Kim Phillips <kim.phillips@freescale.com>
[Kevin: Original patch taken from FSL
QorIQ-SDK-V1.2-SOURCE-20120614-yocto.iso image]
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>