fsl_qbman: update the using of do_mmap due to API change
commit 156851e9f5028bd684d49a0a7c0b1907c3815ff0 from
https://github.com/nxp-imx/linux-imx.git

Cope with upstream change:
0cac1da5886c ("mm: Re-introduce vm_flags to do_mmap()")

../drivers/staging/fsl_qbman/fsl_usdpaa.c: In function ‘portal_mmap’:
../drivers/staging/fsl_qbman/fsl_usdpaa.c:1404:59: error: passing argument 7 of ‘do_mmap’ makes integer from pointer without a cast [-Werror=int-conversion]
 1404 |                                 res->start >> PAGE_SHIFT, &populate, NULL);
      |                                                           ^~~~~~~~~
      |                                                           |
      |                                                           long unsigned int *

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>