mtd: spi_nor: fix build issue for S25FL{064|128|256}L
commit 4e35f5591b43 (mtd: spi-nor: Use CLSR command for FL-L chips) and
commit c9d6aaec411f (mtd/spi-nor: enable USE_CLSR capability for Cypress
FL-L product family) are based on kernel v5.15, after commit 51c55506a7b1
(mtd: spi-nor: spansion: convert USE_CLSR to a manufacturer flag), there
will be build issue below. According to this commit to fix it.

drivers/mtd/spi-nor/spansion.c: In function 'spi_nor_s25fl_l_sr_ready':
drivers/mtd/spi-nor/spansion.c:554:26: error: 'SNOR_F_USE_CLSR' undeclared (first use in this function)
  554 |         if (nor->flags & SNOR_F_USE_CLSR && sr[1] & (SR_E_ERR | SR_P_ERR)) {
      |                          ^~~~~~~~~~~~~~~
drivers/mtd/spi-nor/spansion.c:554:26: note: each undeclared identifier is reported only once for each function it appears in
drivers/mtd/spi-nor/spansion.c:560:17: error: implicit declaration of function 'spi_nor_clear_sr'; did you mean 'spi_nor_read_sr'? [-Werror=implicit-function-declaration]
  560 |                 spi_nor_clear_sr(nor);
      |                 ^~~~~~~~~~~~~~~~
      |                 spi_nor_read_sr
drivers/mtd/spi-nor/spansion.c: In function 'spansion_nor_sr_ready_and_clear':
drivers/mtd/spi-nor/spansion.c:588:68: error: too few arguments to function 'spi_nor_read_id'
  588 |         const struct flash_info *tmpinfo = nor->info ? nor->info : spi_nor_read_id(nor);
      |                                                                    ^~~~~~~~~~~~~~~
In file included from drivers/mtd/spi-nor/spansion.c:9:
drivers/mtd/spi-nor/core.h:652:5: note: declared here
  652 | int spi_nor_read_id(struct spi_nor *nor, u8 naddr, u8 ndummy, u8 *id,
      |     ^~~~~~~~~~~~~~~

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>