MA-19046 clk: imx8mm: Support building clk-imx8mm driver as module
commit 602af3ef7c55c1592ea17b9d09028e1a67671d6c from
https://github.com/nxp-imx/linux-imx

Remove late_initcall(pll_debug_init) definition when building it
as module, to fix below build error:
    drivers/clk/imx/clk-imx8mm.c:742:1: error: redefinition of '__inittest'
    late_initcall(pll_debug_init);

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Jacky Bai <ping.bai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>