LF-1162-10 gpu: drm: bridge: it6263: include correct headfile for DRM_ERROR
commit 93c1143d4242349822ff557f78e8a683d78c9b61 from
https://github.com/nxp-imx/linux-imx

../drivers/gpu/drm/bridge/it6263.c: In function ‘it6263_bridge_attach’:
../drivers/gpu/drm/bridge/it6263.c:729:3: error: implicit declaration of function ‘DRM_ERROR’; did you mean ‘DDC_ERROR’? [-Werror=implicit-function-declaration]
  729 |   DRM_ERROR("Fix bridge driver to make connector optional!");

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>