LF-9958-2 media: Samsung CSI2: fix build error due to API change
commit b98cd38283d88a37e1ff1e31b1d73ff40cb0e84f from
https://github.com/nxp-imx/linux-imx.git

Fix following build error.

drivers/staging/media/imx/imx8-mipi-csi2-sam.c:428:37: error: field 'asd' has incomplete type
  428 |         struct v4l2_async_subdev    asd;
      |                                     ^~~

caused by
commit adb2dcd5f2d4 ("media: v4l: async: Rename v4l2_async_subdev as v4l2_async_connection")

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>