media: chips-media: wave5: initialize variable
commit 2faf22c00003556294f53007c8d6bfb18ef4fb51 from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

Initialize ret variable in two functions to fix build issue:
 wave5-helper.c:268:6: error: variable 'ret' is used uninitialized
 whenever 'if' condition is false [-Werror,-W sometimes-uninitialized]

Fixes: c08bc57d0e3e ("media: chips-media: wave5: Add Support for Frequency Points")
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>