bpf: Fix the indention issue in grow_stack_state()
The commit 81c12119c23f ("bpf: Fix accesses to uninit stack slots") was
backported from upstream, but the indention of some codes were mangled
when doing the backport. Fix them to suppress the following build error
when CONFIG_WERROR is enabled:
  kernel/bpf/verifier.c:866:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
    866 |     if (env->subprog_info[state->subprogno].stack_depth < size)
        |     ^~

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>