soc: marvell: hw-access: fix modpost errors
commit f1ec2a1457fb4b1aff6d01f7b6e595ca6d8d110d from
git@git.assembla.com:cavium/WindRiver.linux.git

hw-access drivers makes use of functions from Marvells
OCTEONTX2_AF driver. Fix Kbuild dependency for that case.

Fixes:
ERROR: modpost: "rvu_mbox_handler_nix_aq_enq"
[drivers/soc/marvell/hw-access/hw_access.ko] undefined!
ERROR: modpost: "rvu_mbox_handler_npa_aq_enq"
[drivers/soc/marvell/hw-access/hw_access.ko] undefined!

Fixes: 5f6343947e20 ("soc: marvell: Driver to access and modify device CSRs.")

Change-Id: I56b32db64bff9649b92a7e29f4c76b453fecb3d7
Signed-off-by: Wladislav Wiebe <wladislav.wiebe@nokia.com>
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/118242
Reviewed-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
Tested-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>