usb: dwc3: define dummy dwc3_host_wakeup_* APIs for DWC3_GADGET mode
commit 69d069e4b6ffc0c9ba806678fe73e6a1868954ea from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.6

Define dwc3_host_wakeup_register() and dwc3_host_wakeup_capable()
dummy APIs for dwc3 gadget mode. It fixes the below compilation error
when DWC3 is configured for gadget only mode.

aarch64-xilinx-linux-ld.real: drivers/usb/dwc3/dwc3-xilinx.o:
in function `dwc3_xlnx_probe':
dwc3-xilinx.c:(.text+0x504): undefined reference to
`dwc3_host_wakeup_register'
aarch64-xilinx-linux-ld.real: drivers/usb/dwc3/dwc3-xilinx.o:
in function `dwc3_xlnx_remove':
dwc3-xilinx.c:(.text+0xb1c): undefined reference to
`dwc3_host_wakeup_register'
aarch64-xilinx-linux-ld.real: drivers/usb/host/xhci-plat.o:
in function `xhci_plat_probe':
xhci-plat.c:(.text+0x790): undefined reference to
`dwc3_host_wakeup_capable'

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>