media: microchip: fix an unused-but-set warning
commit 76499802b1c26e4fe80d120a3cdbb8739c966a7b from
https://github.com/linux4microchip/linux.git linux-6.6-mchp+fpga

Clang allmodconfig builds report:
../drivers/media/platform/microchip/microchip-vcpp.c:788:25: error: variable 'mchp_vcpp' set but not used [-Werror,-Wunused-but-set-variable]
        struct mchp_vcpp_fpga *mchp_vcpp;

Drop the variable, and cull the unneeded switch statement in the
process.

Signed-off-by: Conor Dooley <conor.dooley@microchip.com>
Signed-off-by: harish h <harish.h@windriver.com>