LF-1011-27 arm: imx: pm-imx7ulp: fix build break when calling of_flat_dt_match
commit a8e82f782bd77ac286bb89658a8bc76039058aee from
https://source.codeaurora.org/external/imx/linux-imx

Old API was hiddened from user.

../arch/arm/mach-imx/pm-imx7ulp.c: In function ‘imx7ulp_dt_find_lpsram’:
../arch/arm/mach-imx/pm-imx7ulp.c:559:6: error: implicit declaration of function ‘of_flat_dt_match’ [-Werror=implicit-function-declaration]
  559 |  if (of_flat_dt_match(node, low_power_ocram_match)) {
      |      ^~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>