MLK-21876-10 gpu: drm: dpu: fix headfile reference issue (part 1)
commit 2318cff9f5def04b8e7bc6b4ff290e06a10c7d02 from
https://github.com/nxp-imx/linux-imx.git

../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>