MLK-21985-1 arm64: dts: imx8mq: fix vpu dts build error
commit 9d5dfb0f016e7da4e8f47f346ce33324d15b21f9 from
https://source.codeaurora.org/external/imx/linux-imx

../arch/arm64/boot/dts/freescale/imx8mq.dtsi:1074.21-1088.5: ERROR (phandle_references): /soc@0/vpu@38300000: Reference to non-existent node or label "sw1c_reg"

ERROR: Input tree has errors, aborting (use -f to force output)
scripts/Makefile.lib:297: recipe for target 'arch/arm64/boot/dts/freescale/imx8mq-librem5-devkit.dtb' failed
make[3]: *** [arch/arm64/boot/dts/freescale/imx8mq-librem5-devkit.dtb] Error 2

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>