ASoC: fsl_sai: Fix wrong usage of fsl_sai::is_consumer_mode in fsl_sai_hw_params()
The SDK commit 3fc9d125f615 ("ASoC: fsl_sai: add fsl,txm-rxs property
support") has changed fsl_sai::is_consumer_mode to an array of bool.
But the stable commit 4a8774a63303 ("ASoC: fsl_sai: Fix no frame sync
clock issue on i.MX8MP") still use it as a bool. Adjust the codes from
the stable kernel update to fix the following build errors:
  sound/soc/fsl/fsl_sai.c: In function ‘fsl_sai_hw_params’:
  sound/soc/fsl/fsl_sai.c:697:13: error: the comparison will always evaluate as ‘true’ for the address of ‘is_consumer_mode’ will never be NULL [-Werror=address
  ]
    697 |             !sai->is_consumer_mode)
        |             ^

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>