clk: si5324: fix linking failure for ARCH arm
commit c08f6d78a0fa64044e54ee4099ee6e51fdcaa2e1 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

64-bit division "(u64 A) / (u32 B)" will break linking on ARCH arm:

arm-linux-gnueabihf-ld: drivers/clk/si5324drv.o: in function `si5324_find_n2ls':
si5324drv.c:(.text+0xb94): undefined reference to `__aeabi_uldivmod'

Fix this by using do_div.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>