firmware: arch64: Fix SMC call testing module for kernel 5.10
commit 743e7b41ea1fd16869a50e21920c371c77069d49 from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

drivers/firmware/smc_latency.c:338:10: error: passing argument 4 of
   'proc_create' from incompatible pointer type
   [-Werror=incompatible-pointer-types]

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>