LF-1197-2 gpu: drm: imx: ipuv3: remove drmP.h
commit 0c443d50a507ab8a9c3257b299f8cce8b42ab599 from
https://github.com/nxp-imx/linux-imx.git

API changes:
4e98f871bcff ("drm: delete drmP.h + drm_os_linux.h")

drivers/gpu/drm/imx/ipuv3/ipuv3-kms.c:15:10: fatal error: drm/drmP.h: No such file or directory
   15 | #include <drm/drmP.h>

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>