LF-9968 media: parallel: fix build error due to api change
commit c6ef63fafc7f51f2e675571238c4d4d7f19ab3da from
https://github.com/nxp-imx/linux-imx.git

drivers/staging/media/imx/imx8-parallel-csi.c:186:41: error: field 'asd' has incomplete type
  186 |         struct v4l2_async_subdev        asd;
      |                                         ^~~

caused by
commit adb2dcd5f2d4 ("media: v4l: async: Rename v4l2_async_subdev as v4l2_async_connection")

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>