tty: serial: lpuart: Fix a build error: 'irq_wake' undeclared
Due to the patch conflict of 7e221e7441f1 commit
("tty: serial: lpuart: enable wakeup source for lpuart"),
the compilation error is caused, so this patch is used
to resolve this conflict.

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>