OF: DT-Overlay: Drop the unused overlay_lock in configfs.c
This overlay_lock was introduced by commit 6d4653237dc37 ("OF:
DT-Overlay configfs interface (v8)"), but it was never used since then.
Drop it to fix the below build error:
  drivers/of/configfs.c:46:21: error: ‘overlay_lock’ defined but not used [-Werror=unused-variable]
     46 | static DEFINE_MUTEX(overlay_lock);
        |                     ^~~~~~~~~~~~

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>