MLK-21876-10 gpu: drm: lcdif: fix headfile reference issue
commit a36a2be270e58543607f4002c6ccfc9972e3d69a from
https://source.codeaurora.org/external/imx/linux-imx

  CC      drivers/gpu/drm/imx/lcdif/lcdif-crtc.o
../drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:26:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>