dpaa2-eth: replace struct "gnet_stats_basic_packed" with "gnet_stats_basic_sync"
commit 304640d0b862(net: sched: Merge Qdisc::bstats and Qdisc::cpu_bstats data types)
has dropped the struct "gnet_stats_basic_packed", replaced with "gnet_stats_basic_sync".
Here adapt to this changes.

And using the API u64_stats_add() to avoid below building error:
dpaa2-eth-ceetm.c:380:49: error: invalid operands to binary + (have 'u64_stats_t' and 'u64_stats_t')
|   380 |                         sch->bstats.bytes       += qdisc->bstats.bytes;
|       |                                                 ^~ ~~~~~~~~~~~~~~~~~~~
|       |                                                                 |
|       |                                                                 u64_stats_t

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>