LF-6810-01: media: parallel: fix build error due to API renamed
commit bea994d4a819f09e0388dc90e7ad83fcada0cbed from
https://github.com/nxp-imx/linux-imx

drivers/staging/media/imx/imx8-parallel-csi.c:427:46:
error: implicit declaration of function ‘media_entity_remote_pad’; did you mean ‘media_entity_remove_links’? [-Werror=implicit-function-declaration]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
 media_pad_remote_pad_first())

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <Robby.Cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>