MA-20021-1 thermal: device_cooling: Fix duplicate symbol build error
commit 1245852e43ebfee9589663ba43c499333b65b529 from
https://github.com/nxp-imx/linux-imx.git

devfreq_cooling_register and devfreq_cooling_unregister
are both exported by devfreq_cooling.c and device_cooling.c.
So modify these symbol names to pass building.

ld.lld: error: duplicate symbol: devfreq_cooling_register
>>> defined at devfreq_cooling.c:455 (/home/ssd-2/jindong/r1/vendor/nxp-opensource/kernel_imx/drivers/thermal/devfreq_cooling.c:455)
>>>            thermal/devfreq_cooling.o:(devfreq_cooling_register) in archive drivers/built-in.a
>>> defined at device_cooling.c:110 (/home/ssd-2/jindong/r1/vendor/nxp-opensource/kernel_imx/drivers/thermal/device_cooling.c:110)
>>>            thermal/device_cooling.o:(.text+0x50) in archive drivers/built-in.a

ld.lld: error: duplicate symbol: devfreq_cooling_unregister
>>> defined at devfreq_cooling.c:511 (/home/ssd-2/jindong/r1/vendor/nxp-opensource/kernel_imx/drivers/thermal/devfreq_cooling.c:511)
>>>            thermal/devfreq_cooling.o:(devfreq_cooling_unregister) in archive drivers/built-in.a
>>> defined at device_cooling.c:145 (/home/ssd-2/jindong/r1/vendor/nxp-opensource/kernel_imx/drivers/thermal/device_cooling.c:145)
>>>            thermal/device_cooling.o:(.text+0x1D4) in archive drivers/built-in.a

Change-Id: Ibe69fd26179dc130659c1376d95fc9976eaf3d84
Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>