i2c: microchip-core: fix -Wsometimes-uninitialized error in sbmus code
commit a563861b8b05dd5cd4a2f926d62a441db92767c3 from
https://github.com/linux4microchip/linux.git linux-6.6-mchp+fpga

Clang reports:
i2c-microchip-corei2c.c:446:7: error: variable 'ret' is used uninitialized whenever switch case is taken [-Werror,-Wsometimes-uninitialized]
        case I2C_SMBUS_QUICK:

Initialise the variable in that case to elide the warning.

Signed-off-by: Conor Dooley <conor.dooley@microchip.com>
Signed-off-by: harish h <harish.h@windriver.com>