LF-6783: drm: imx_mhdp: fix build error
commit 775aefca50b02a9a8a75ccadf084f7f4e436aba6 from
https://github.com/nxp-imx/linux-imx

Fix the build error for LF_NEXT_L5.19_RC7_20220719

CC [M] drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.o
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:103:19: error: ‘MEDIA_BUS_FMT_RGB101010_1X30’ undeclared here (not in a function)
103 | .video_format = MEDIA_BUS_FMT_RGB101010_1X30,

Signed-off-by: Sandor Yu <Sandor.yu@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>