firmware: stratix10-svc: remove invalid label err_free_kfifo added by merge conflict
Merge commit: 3be3c294da42 ("Merge branch 'v5.15/standard/base' into
v5.15/standard/intel-sdk-5.15/intel-socfpga") added an invalid label
err_free_kfifo which already dropped in commit 4e779fd561b5
("HSD #14015013554: firmware: stratix10-svc: Support up to 4 SVC clients")
this will cause below build error, remove it to fix this.

drivers/firmware/stratix10-svc.c: In function ‘stratix10_svc_drv_probe’:
drivers/firmware/stratix10-svc.c:1737:24: error: ‘struct stratix10_svc_controller’ has no member named ‘svc_fifo’
  kfifo_free(&controller->svc_fifo);

Signed-off-by: Liwei Song <liwei.song@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>