MLK-21876-10 gpu: drm: ipu: fix headfile reference issue (part2)
commit eabd4e762217e9368fefc63308222388257cdbdc from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>