drm: xlnx: Update DSI-Tx Kconfig
commit 658e7e89afe4a21ab53dc9367309065c9a064569 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

This patch fixes the following compilation errors on disabling
CONFIG_PM and CONFIG_SUSPEND.
drivers/gpu/drm/panel/panel-simple.c:5316: undefined reference to
`__dp_aux_dp_driver_register'

Xilinx DSI-TX Host driver should work with any panel driver.
Hence removing panel driver selection from DSI Kconfig

Signed-off-by: Venkateshwar Rao Gannavarapu <venkateshwar.rao.gannavarapu@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>