MLK-21876-11 gpu: fix build for next-20190524 upgrade
commit daf001a9a48fde0c02072b86496ba4ee6dfb228d from
https://github.com/nxp-imx/linux-imx.git

Failed on imx v6_v7 build.

../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:86:17: fatal error: dma.h: No such file or directory
 #include <dma.h>
                 ^
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>