omap3-trace-clock-header-moved-to-plat
omap3 trace clock header moved to plat

Fixes:

CC      arch/arm/mach-omap2/pm34xx.o
In file included from
/home/fabroy01/src/linux-2.6-lttng/arch/arm/include/asm/trace-clock.h:1,
                 from arch/arm/mach-omap2/pm34xx.c:45:
arch/arm/mach-omap2/include/mach/trace-clock.h:12: fatal error:
mach/clock.h: No such file or directory
compilation terminated.

Also updates the plat/ header including missing bits from the mach/ header.
Remove the now unused mach/ header to complete transition.

Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>