LF-6810-04: media: isi cap: fix build error due to API renamed
commit 28145b2740ae3fe837745f755f7824a4bd56379b from
https://github.com/nxp-imx/linux-imx.git

Fix ISI capture driver build error due to API renamed in bellow commit:
drivers/staging/media/imx/imx8-isi-cap.c:602:46:
error: implicit declaration of function ‘media_entity_remote_pad’; did you mean ‘media_entity_remove_links’? [-Werror=implicit-function-declaration]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
 media_pad_remote_pad_first())

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <Robby.Cai@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>