media: platform: dwc: fix misleading indentation
commit dd16129714a96e42c8f7bbae00b1749385b6d49f from
https://github.com/linux4microchip/linux.git linux-6.6-mchp+fpga

This patch fixes the misleading indentation warning on GCC 11+:

drivers/media/platform/dwc/dw-csi-plat.c: In function ‘dw_csi_probe’:
drivers/media/platform/dwc/dw-csi-plat.c:541:9: error: this ‘else’ clause
does not guard... [-Werror=misleading-indentation]
  541 |         else
      |         ^~~~
drivers/media/platform/dwc/dw-csi-plat.c:544:17: note: ...this statement,
but the latter is misleadingly indented as if it were guarded by the ‘else’
  544 |                 goto end;
      |                 ^~~~

Fixes: 11bcf7b8d3c9 ("media: platform: dwc: Add MIPI CSI-2 controller driver")
Signed-off-by: Cristian Birsan <cristian.birsan@microchip.com>
Signed-off-by: harish h <harish.h@windriver.com>