drm: xlnx: Update DSI-Tx Kconfig
commit d8225a58e19604aa24b5808aebcb92a67dc9c83a from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.1

This patch fixes the following compilation errors on disabling
CONFIG_PM and CONFIG_SUSPEND.
drivers/gpu/drm/panel/panel-simple.c:5316: undefined reference to
`__dp_aux_dp_driver_register'

Xilinx DSI-TX Host driver should work with any panel driver.
Hence removing panel driver selection from DSI Kconfig

Signed-off-by: Venkateshwar Rao Gannavarapu <venkateshwar.rao.gannavarapu@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>