firmware: stratix10-svc: replace size by pmem->size to avoid undeclared error
The build error is introduced by merge commit:
f3d210c72471 ("Merge branch 'v5.15-pull-0616-merge' into v5.15/standard/intel-sdk-5.15/intel-socfpga")

since the definition of "size" is removed, replace it by the same
definition "pmem->size" to fix below build error, adjust list_del
to make it consistent with upstream.

drivers/firmware/stratix10-svc.c: In function 'stratix10_svc_free_memory':
drivers/firmware/stratix10-svc.c:1591:26: error: 'size' undeclared (first use in this function); did you mean 'ksize'?
  1591 |         memset(kaddr, 0, size);
       |                          ^~~~
       |                          ksize
drivers/firmware/stratix10-svc.c:1591:26: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Liwei Song <liwei.song@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>