usb: dwc3: Fix Axxia xHCI DWC3 USB driver for kernel 5.10
commit 5b169719268e0eacff2cd042150dfc851858cc5f from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

drivers/usb/dwc3/dwc3-axxia.c:131:3: error: implicit declaration
of function 'arch_setup_dma_ops' [-Werror=implicit-function-declaration]

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>