LF-1011-23 gpu: drm: bridge: dsim: update using of drm_panel_get_modes
commit af9b9b512eaf4e674207dc2563682dcc2831f771 from
https://github.com/nxp-imx/linux-imx.git

API changed since:
0ce8ddd8e06d ("drm/panel: add drm_connector argument to get_modes()")

../drivers/gpu/drm/bridge/sec-dsim.c: In function ‘sec_mipi_dsim_connector_get_modes’:
../drivers/gpu/drm/bridge/sec-dsim.c:1798:9: error: too few arguments to function ‘drm_panel_get_modes’
 1798 |  return drm_panel_get_modes(dsim->panel);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>