MA-20197-3 uapi: mxc_v4l2: use __u32 instead of uint32_t
commit  0374a315362cabbc16e3c3fa0e42a9c07c7f336b from
https://github.com/nxp-imx/linux-imx lf-6.1.y

Enable CONFIG_UAPI_HEADER_TEST turns on the following build issue:
./usr/include/linux/mxc_v4l2.h:52:2: error: unknown type name 'uint32_t'
        uint32_t u_offset;
        ^
./usr/include/linux/mxc_v4l2.h:53:2: error: unknown type name 'uint32_t'
        uint32_t v_offset;
        ^
./usr/include/linux/mxc_v4l2.h:57:2: error: unknown type name '__u32'
        __u32                   type;   /* enum v4l2_buf_type */
        ^

To fix it, use __u32 instead of uint32_t and include linux/types.h.

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>