irqchip/gic-v3: Fix undeclared error for 'NR_IPI' macro
commit 12cd466cc89cf02de4cffdc6d74b0ce099a5ba5b from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

drivers/irqchip/irq-gic-v3.c:1077:38: error: 'NR_IPI' undeclared
(first use in this function)

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>