staging: xilinx-tsn: Fix compilation error in xilinx-tsn when PHYLIB is configured as a module.
commit 001dc1414212b68c58559e1757fa1986d30d210c from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

TSN depends on PHYLIB. Adding this dependency to xilinx-tsn Kconfig.

Results in following errors when this dependency is not included:
aarch64-xilinx-linux-ld.real: drivers/staging/xilinx-tsn/xilinx_tsn_ip.o: in function `axienet_tsn_open':
xilinx_tsn_ip.c:(.text+0xd10): undefined reference to `of_phy_connect'
aarch64-xilinx-linux-ld.real: xilinx_tsn_ip.c:(.text+0xd48): undefined reference to `phy_start'
arch64-xilinx-linux-ld.real: drivers/staging/xilinx-tsn/xilinx_tsn_ip.o: in function `axienet_tsn_stop':
xilinx_tsn_ip.c:(.text+0x115c): undefined reference to `phy_disconnect'

Signed-off-by: Pranavi Somisetty <pranavi.somisetty@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>