SPEAr: fix missing include file jiffies.h
To fix following compile error:
...
In function 'boot_secondary':
error: 'jiffies' undeclared (first use in this function)
error: implicit declaration of function 'time_before'
...

Signed-off-by: Liming Wang <liming.wang@windriver.com>