MLK-21876-10 gpu: drm: ipu: fix headfile reference issue (part2)
commit 2d5035ec9a0e28757719a1ba01818bb91d7d99e3 from
https://github.com/nxp-imx/linux-imx

../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>