MA-20005-13 hantro_v4l2: Fix build error exposed by -Wshift-count-overflow
commit 5b8b7d54ad5549b4b2be4bcb19a08567af89f7d8 from
https://github.com/nxp-imx/linux-imx.git

Fix below build error:
drivers/mxc/hantro_v4l2/vsi-v4l2.c:699:14: error: shift count >= width of type [-Werror,-Wshift-count-overflow]
        .dma_mask       = DMA_BIT_MASK(64),
                          ^~~~~~~~~~~~~~~~
include/linux/dma-mapping.h:76:54: note: expanded from macro 'DMA_BIT_MASK'
                                                     ^ ~~~

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Shijie Qin <shijie.qin@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>