of: configfs: remove unused variable overlay_lock
remove unused variable "overlay_lock" that introduced in
a75774679f28 ("OF: DT-Overlay configfs interface (v8)")
to fix below compile error:

| drivers/of/configfs.c:46:21: error: 'overlay_lock' defined but not used [-Werror=unused-variable]
|    46 | static DEFINE_MUTEX(overlay_lock);
|       |                     ^~~~~~~~~~~~

Signed-off-by: Liwei Song <liwei.song@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>