intel: fcs: remove unused variable total_out_size and output_file_pointer
total_out_size and output_file_pointer are not used anymore, delete them
to avoid build error when enabled [-Werror=unused-variable]:

drivers/crypto/intel_fcs_main.c:
In function 'fcs_ioctl':
|
drivers/crypto/intel_fcs_main.c:403:45:
error: unused variable 'total_out_size' [-Werror=unused-variable]
|   403 |         uint32_t remaining_size, data_size, total_out_size;
|       |                                             ^~~~~~~~~~~~~~
|
drivers/crypto/intel_fcs_main.c:401:15:
error: unused variable 'output_file_pointer' [-Werror=unused-variable]
|   401 |         void *output_file_pointer;
|       |               ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Liwei Song <liwei.song@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>