v4l: xilinx: hls: Fix the uapi header license
commit 79fbadee637982230bb52f37c151d169bf3cef77 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.1

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>