PCI: j721e: j784s4 disables retrain Link for Gen2 training
The quirk_retrain_flag = true is to retrain link for Gen2 training,
however this will cause LINKDOWN and below call trace, here set the flag
to false to fix this issue.

l Abort received on 0x80000000 from S-EL1
ERROR: exception reason=0 syndrome=0xbf000000
Unhandled Exception from EL1

x0 = 0xfffffe000c6c0000
x1 = 0x0000000000000000
x2 = 0xfffffe0010c00008
x3 = 0x0000000000000001
x4 = 0x000000000000000b
x5 = 0xfffffc0804578800
x6 = 0x0000000000000001
x7 = 0x0000000000000000
x8 = 0xfffffe0009cef710
x9 = 0xfffffe00086536dc
x10 = 0x0101010101010101
x11 = 0x0000000000000028
x12 = 0x666e6f636572202c
x13 = 0xfffffc08001f229a
x14 = 0xffffffffffffffff
x15 = 0xfffffc08001f2a1c
x16 = 0x000013dfbf08dc14
x17 = 0x0000000000000002
x18 = 0xffffffffffffffff
x19 = 0x0000000000000004
x20 = 0xfffffe0009cef7b4
x21 = 0x0000000000000087
x22 = 0xfffffe0009cef854
x23 = 0x0000000000000000
x24 = 0xfffffe0009812fa0
x25 = 0x0000000000000001
x26 = 0xfffffc08045790e0
x27 = 0xfffffe0009658eb8
x28 = 0xfffffc0804578800
x29 = 0xfffffe0009cef740
x30 = 0xfffffe0008626aec
scr_el3 = 0x000000000000073d
sctlr_el3 = 0x0000000030cd183f
cptr_el3 = 0x0000000000000000
tcr_el3 = 0x0000000080803520
daif = 0x00000000000002c0
mair_el3 = 0x00000000004404ff
spsr_el3 = 0x00000000200000c5
elr_el3 = 0xfffffe0008626b04
ttbr0_el3 = 0x0000000070011cc0
esr_el3 = 0x00000000bf000000
far_el3 = 0x0000000000000000
spsr_el1 = 0x0000000000000005
elr_el1 = 0xfffffe0008073a90
spsr_abt = 0x0000000000000000
spsr_und = 0x0000000000000000
spsr_irq = 0x0000000000000000
spsr_fiq = 0x0000000000000000
sctlr_el1 = 0x0000000034d4d91d
actlr_el1 = 0x0000000000000000
cpacr_el1 = 0x0000000000300000
csselr_el1 = 0x0000000000000000
sp_el1 = 0xfffffe0009cef740
esr_el1 = 0x0000000000000000
ttbr0_el1 = 0x0000000083070000
ttbr1_el1 = 0x0000000083080000

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>