mmc: Fix the warning of mmc when CPU is being in sleep mode.
When CPU is being put to sleep by echoing "standby" to
/sys/power/state, the below kernel warning is generated.

sysfs: kobject mmcblk0 without dirent
------------[ cut here ]------------
WARNING: at
linux-windriver-3.4-r0/linux/fs/sysfs/file.c:498

Modules linked in:
NIP: c01c1b20 LR: c01c1b20 CTR: c0494a20
REGS: ef311c20 TRAP: 0700   Not tainted  (3.4.10-WR5.0.0.0_standard+)
MSR: 00029000 <CE,EE,ME>  CR: 22442684  XER: 00000000
TASK = ef9985a0[791] 'sh' THREAD: ef310000 CPU: 1
GPR00: c01c1b20 ef311cd0 ef9985a0 0000002c 00021000 fffffff	c0420250 0001ffff
GPR08: c0903344 c089f2c4 00000001 00f6f000 82442622 100f485	00000000 00000000
GPR16: 100ecee0 100f0000 100f0000 100f0000 100fb908 10116568 0000000 00000000
GPR24: c06f5850 ffffffed c0796730 00000008 ef16e000 ef16e000 ef16ae68 ef16e290
NIP [c01c1b20] sysfs_attr_ns+0xb8/0xd0
LR [c01c1b20] sysfs_attr_ns+0xb8/0xd0
Call Trace:
[ef311cd0] [c01c1b20] sysfs_attr_ns+0xb8/0xd0 (unreliable)
[ef311ce0] [c01c1b64] sysfs_remove_file+0x2c/0x58
[ef311d00] [c042bac0] device_remove_file+0x28/0x38
[ef311d10] [c056eb34] mmc_blk_remove_req+0x44/0xb4
[ef311d20] [c0570ecc] mmc_blk_remove+0xbc/0xdc
[ef311d40] [c0563e38] mmc_bus_remove+0x2c/0x40
[ef311d50] [c042f314] __device_release_driver+0x74/0xd8
[ef311d60] [c042f3ac] device_release_driver+0x34/0x50
[ef311d70] [c042ed54] bus_remove_device+0xe8/0x120
[ef311d90] [c042bcd0] device_del+0x120/0x1b8
[ef311db0] [c056456c] mmc_remove_card+0x6c/0xb0
[ef311dc0] [c0567da8] mmc_sd_remove+0x40/0x5c
[ef311dd0] [c0563d60] mmc_pm_notify+0xe4/0x128
[ef311df0] [c06ac0a0] notifier_call_chain+0x70/0xc0
[ef311e20] [c006ede4] __blocking_notifier_call_chain+0x5c/0x80
[ef311e40] [c006ee2c] blocking_notifier_call_chain+0x24/0x34
[ef311e50] [c0089048] pm_notifier_call_chain+0x30/0x54
[ef311e60] [c0089df8] pm_suspend+0xf0/0x1f0
[ef311e80] [c0088bd0] state_store+0xa8/0xec
[ef311ea0] [c03be6cc] kobj_attr_store+0x24/0x3c
[ef311eb0] [c01c11d8] sysfs_write_file+0x104/0x1a4
[ef311ee0] [c0152a64] vfs_write+0xb4/0x178
[ef311f00] [c0152e34] sys_write+0x5c/0x138
[ef311f40] [c00106ac] ret_from_syscall+0x0/0x3c
    Exception: c01 at 0xff0e034
       LR = 0xfeb3444
Instruction dump:
90a10008 484eeaf9 0fe00000 80a10008 38000000 3860ffea 90050000 4800001c
80830000 3c60c07b 3863e460 484eead1 <0fe00000> 3860fffe 80010014 7c0803a6
       ---[ end trace f237af926214a6cc ]---

The issue is introduced by our patch. The following is the commit log of
our patch.
[
SD/MMC: Add an interface to re-initialize the bounce buffer

Add bounce_size under /sys/block/mmcblk0/bouncesz. Support dynamic adjustment of
bounce buffer in run-time (include mounted or unmounted filesystem)

/sys/block/mmcblk0/bouncesz should be integer multiple of 512, the value should
be range from 4096 to 4194304
]

We cannot delete the attribute of a device (bouncesz) after we've
removed the disk via del_gendisk(). So we move the deletion of the
attribute to before the disk is removed.

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>