MLK-13470 mfd: max17135: export symbols to fix build error as a module
commit 6852169e507b76c03a05d8f68ea96dbe1b4cde28 from
https://github.com/nxp-imx/linux-imx.git

export symbols to fix build error as a module:

ERROR: "max17135_reg_read" [drivers/hwmon/max17135-hwmon.ko] undefined!

Signed-off-by: Julien Olivain <julien.olivain@nxp.com>
Acked-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>