drm: bridge: it6161: add missing gpio consumer header
commit 1470539d323d99fbe45e3f26cab3a86e5dd5182c from
https://github.com/nxp-imx/linux-imx.git

Fix it6161.c:2810:24: error: implicit declaration of function
'devm_gpiod_get_optional'.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
Acked-by: Jason Liu <jason.hui.liu@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>