crypto: tls - Use data directly in completion function
commit b32926ef04377ccf6ffcfc27b6dcea98b531d248 from
https://github.com/nxp-imx/linux-imx.git

Facing build error in building tls
error: passing argument 3 of ?ahash_request_set_callback?
from incompatible pointer type [-Werror=incompatible-pointer-types]

Issue introduced after changing prototype of "crypto_completion_t"
function pointer in include/linux/crypto.h, conversion of
completion function of tls was missed.

Changes are done to use data directly in completion function of tls.

Fixes: 255e48eb1768 ("crypto: api - Use data directly in completion function")
Signed-off-by: Meenakshi Aggarwal <meenakshi.aggarwal@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>