LF-1011-29 arm: imx: fix build break when calling of_flat_dt_match
commit 4dc07cd7bd9c58fe38f81d7fa2968cd9ac02e4cf from
https://github.com/nxp-imx/linux-imx.git

Old API was hiddened from user.

../arch/arm/mach-imx/busfreq-imx.c: In function ‘imx_dt_find_ddr_sram’:
../arch/arm/mach-imx/busfreq-imx.c:962:6: error: implicit declaration of function ‘of_flat_dt_match’; did you mean ‘of_flat_dt_match_machine’? [-Werror=implicit-function-declaration]
  962 |  if (of_flat_dt_match(node, ddr_freq_iram_match)) {

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>