drm: bridge: it6161: add missing gpio consumer header
commit a2c0ef6ccaa4ae3a9bd8358b5235d72115c499d0 from
https://github.com/nxp-imx/linux-imx

Fix it6161.c:2810:24: error: implicit declaration of function
'devm_gpiod_get_optional'.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
Acked-by: Jason Liu <jason.hui.liu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>