LF-1011-22 gpu: drm: bridge: dsim: remove the using of bridge->next
commit fcd177c84add4d46bc508ed0adc9a981223c4f21 from
https://github.com/nxp-imx/linux-imx.git

API changed since:
05193dc38197 ("drm/bridge: Make the bridge chain a double-linked list")

../drivers/gpu/drm/bridge/sec-dsim.c: In function ‘sec_mipi_dsim_bridge_attach’:
../drivers/gpu/drm/bridge/sec-dsim.c:855:34: error: ‘struct drm_bridge’ has no member named ‘next’
  855 |  WARN_ON(bridge == next || bridge->next || dsim->next);
      |                                  ^~
../include/asm-generic/bug.h:113:25: note: in definition of macro ‘WARN_ON’
  113 |  int __ret_warn_on = !!(condition);    \
      |                         ^~~~~~~~~
../drivers/gpu/drm/bridge/sec-dsim.c:868:8: error: ‘struct drm_bridge’ has no member named ‘next’
  868 |  bridge->next = next;
      |        ^~
../drivers/gpu/drm/bridge/sec-dsim.c: In function ‘sec_mipi_dsim_connector_get_modes’:
../drivers/gpu/drm/bridge/sec-dsim.c:1801:9: error: too few arguments to function ‘drm_panel_get_modes’
 1801 |  return drm_panel_get_modes(dsim->panel);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>