gpio: Fix Axxia GPIO driver for kernel 5.10
commit a51c97ace83e8581aa459467648771e439946eb3 from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

Updated Axxia GPIO driver to support Linux 5.10. Changes
were made to fix compile errors (such as the one below).
Also update the driver to support the spi-nor.

drivers/gpio/gpio-axxia.c:363:4: error: implicit declaration of function
'gpiochip_set_chained_irqchip'; did you mean 'gpiochip_set_nested_irqchip

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Charlie Paul <charlie.paul@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>