MLK-21876-10 gpu: drm: lcdif: fix headfile reference issue
commit 3f6df6d47a9fce561ae353f364c7d633fd932cb5 from
https://github.com/nxp-imx/linux-imx

  CC      drivers/gpu/drm/imx/lcdif/lcdif-crtc.o
../drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:26:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>