MLK-23547: ASoC: SOF: Use machine_drv_name on OF platforms
commit d12caeed0fbe2ebc632ecee5a975466b46666ecf from
https://github.com/nxp-imx/linux-imx

On OF platforms information about machine driver is stored
in sof_pdata->machine_drv_name.

Without this SOF probe fails with:
error: no matching ASoC machine driver found - aborting probe

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>