coresight: etm4x: Handle CS_MODE_READ_PREVBOOT mode in etm4_disable()
A new CS_MODE_READ_PREVBOOT mode was introduced by commit e86129e38029
("coresight: tmc: etr: Add support for Marvell OcteonTX2"), but it was
not added in switch of etm4_disable(). This would emit a build error
like below when CONFIG_WERROR is enabled:
  drivers/hwtracing/coresight/coresight-etm4x-core.c: In function ‘etm4_disable’:
  drivers/hwtracing/coresight/coresight-etm4x-core.c:1050:9: error: enumeration value ‘CS_MODE_READ_PREVBOOT’ not handled in switch [-Werror=switch]
   1050 |         switch (mode) {
        |         ^~~~~~
  cc1: all warnings being treated as errors

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>