powerpc/85xx: fix compile error when CONFIG_HOTPLUG_CPU is disabled
../arch/powerpc/platforms/85xx/smp.c:306:4:
error: implicit declaration of function 'generic_set_cpu_up'
../arch/powerpc/platforms/85xx/smp.c:321:4:
error: implicit declaration of function 'is_core_down'
make[3]: *** [arch/powerpc/platforms/85xx/smp.o] Error 1

Signed-off-by: Zhao Chenhui <chenhui.zhao@freescale.com>
Signed-off-by: Andy Fleming <afleming@freescale.com>
[Kevin: Original patch taken from fsl sdk 1.3.1
QorIQ-SDK-V1.3.1-SOURCE-20121220-yocto.iso. Remove the part
for smp.h since we already pick up that in a previous patch.]
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>