staging: fsl_qbman: include new header file linux/dma-mapping.h
commit 5da9502dee51b31e5f093908e331cc630e061087 from
https://github.com/nxp-imx/linux-imx.git

New headfile introduced from:
0a0f0d8be76d ("dma-mapping: split <linux/dma-mapping.h>")

Including it to fix the build issue below:

drivers/staging/fsl_qbman/qman_high.c: In function ‘qman_create_portal’:
drivers/staging/fsl_qbman/qman_high.c:687:2: error: implicit declaration of function ‘arch_setup_dma_ops’; did you mean ‘arch_setup_new_exec’? [-Werror=implicit-function-declaration]
  arch_setup_dma_ops(&portal->pdev->dev, 0, 0, NULL, true);
  ^~~~~~~~~~~~~~~~~~
  arch_setup_new_exec

Signed-off-by: Li Yang <leoyang.li@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>