mtd: spi-nor: Fix linking failure for ARCH arm
commit d67d21c650c6d72857d8b9e254d0d1256a3c1ca1 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.1

64-bit division "(u64 A) / (u32 B)" will break linking on ARCH arm:

arm-xilinx-linux-gnueabi-ld.real: drivers/mtd/spi-nor/core.o: in function
`spi_nor_read': core.c.text+0x2178): undefined reference to
`__aeabi_ldivmod'

Fix this by using do_div.

Reported-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>
Suggested-by: Michal Simek <michal.simek@amd.com>
Signed-off-by: Amit Kumar Mahapatra <amit.kumar-mahapatra@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>