LF-8221 fbdev: epdc: fix build error for epdc_v2
commit 0a71fc0ea7739301b4fb9c065ce5e0ddfb845deb from
https://github.com/nxp-imx/linux-imx.git

Fix following error caused by the change
a20dacd4c970f gpiolib: of: remove of_get_gpio[_flags]() and of_get_named_gpio_flags()

../drivers/video/fbdev/mxc/mxc_epdc_v2_fb.c: In function 'mxc_epdc_fb_probe':
../drivers/video/fbdev/mxc/mxc_epdc_v2_fb.c:5077:31: error: implicit declaration of function 'of_get_named_gpio_flags'; did you mean 'of_get_named_gpio'? [-Werror=implicit-function-declaration]
 5077 |                 enable_gpio = of_get_named_gpio_flags(np, "en-gpios", 0, &flag);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~
      |                               of_get_named_gpio
cc1: some warnings being treated as errors

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Reviewed-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>