dt-bindings: pinctrl: k3: Introduce pinmux definitions for J721S2
commit 07db379bf062764d6e38c7b30c2bf13b5a9c90e3 from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

commit beba81faad86fc2bad567b1c029d6a000a43ca78 upstream.

Add pinctrl macros for J721S2 SoC. These macro definitions are
similar to that of J721E, but adding new definitions to avoid
any naming confusions in the soc dts files.

checkpatch insists the following error exists:
ERROR: Macros with complex values should be enclosed in parentheses

However, we do not need parentheses enclosing the values for this
macro as we do intend it to generate two separate values as has been
done for other similar platforms.

Signed-off-by: Aswath Govindraju <a-govindraju@ti.com>
Signed-off-by: Vignesh Raghavendra <vigneshr@ti.com>
Reviewed-by: Kishon Vijay Abraham I <kishon@ti.com>
Acked-by: Rob Herring <robh@kernel.org>
Link: https://lore.kernel.org/r/20211207080904.14324-3-a-govindraju@ti.com
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>