drm: tidss: add missing break
commit d4725fb07ca0785d650c559d13989a0460299b1e from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

When we use clang to build with -Wall and -Werror flags we see this issue:

drivers/gpu/drm/tidss/tidss_dispc.c:1068:2: error: unannotated
fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
        default:
        ^

Add missing break in switch case.

Fixes: a04da84be07c ("drm/tidss: Rename AM65x DSS OLDI CTRL MMR registers")
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>
Reviewed-by: Aradhya Bhatia <a-bhatia1@ti.com>
Reviewed-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>
Signed-off-by: Vignesh Raghavendra <vigneshr@ti.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>