LF-1011-29 arm: imx: fix build break when calling of_flat_dt_match
commit 70794f2227dbac7c378c1d95ac7c075f53328dd2 from
https://github.com/nxp-imx/linux-imx

Old API was hiddened from user.

../arch/arm/mach-imx/busfreq-imx.c: In function ‘imx_dt_find_ddr_sram’:
../arch/arm/mach-imx/busfreq-imx.c:962:6: error: implicit declaration of function ‘of_flat_dt_match’; did you mean ‘of_flat_dt_match_machine’? [-Werror=implicit-function-declaration]
  962 |  if (of_flat_dt_match(node, ddr_freq_iram_match)) {

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>