coresight: Move print_arch_cpu_state declaration to a generic header
commit 9d0f2f0a01ef7a8d9f4c939b7604728cb1f0ea77 from
git@git.assembla.com:cavium/WindRiver.linux.git

Move the declaration of print_arch_cpu_state() to generic header file,
include/linux/cpu.h so that it can be reused by other architectures.

Moving this also solves the compiler warning when compiled with
CONFIG_CORESIGHT=n

./include/linux/coresight.h:596:13: error: 'print_arch_cpu_state'
defined but not used [-Werror=unused-function]
  596 | static void print_arch_cpu_state(int cpu) {};
      |             ^~~~~~~~~~~~~~~~~~~~

Change-Id: I0fbd9001314f210f0a65001f8bb6192105bd7f95
Signed-off-by: Tanmay Jagdale <tanmay@marvell.com>
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/115264
Tested-by: sa_ip-sw-jenkins <sa_ip-sw-jenkins@marvell.com>
Reviewed-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>