LF-8513-21 MLK-11444 ata: imx: cmd buf corruption errata bug fix
commit db9daf0cd670bd5642ffe9092da1dce678404a2a from
https://github.com/nxp-imx/linux-imx.git

errata:
When a read command returns less data than specified in the PRDs (for
example, there are two PRDs for this command, but the device returns a
number of bytes which is less than in the first PRD), the second PRD of
this command is  not read out of the PRD FIFO, causing the next command
to use this PRD erroneously.

workaround
- forces sg_tablesize = 1
- modified the sg_io function in block/scsi_ioctl.c to use a 64k buffer
  allocated with dma_alloc_coherent during the probe in ahci_imx
- In order to fix the scsi/sata hang, when CD_ROM and HDD are
  accessed simultaneously after the workaround is applied.
  Do not go to sleep in scsi_eh_handler, when there is host failed.

Upstream kernel mades it const since:
25df73d93323 ("scsi: ata: Declare SCSI host templates const")

Remove SCSI host templates const declaration
But i.MX AHCI local driver needs to make it changable, otherwise:
../drivers/ata/ahci_imx.c: In function ‘imx_ahci_probe’:
../drivers/ata/ahci_imx.c:1050:48: error: assignment of member ‘sg_tablesize’ in read-only object
 1050 |                 ahci_platform_sht.sg_tablesize = 1;
      |                                                ^

Signed-off-by: Richard Zhu <Richard.Zhu@freescale.com>
Signed-off-by: Li Yang <leoyang.li@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>