LF-1197-2 gpu: drm: imx: ipuv3: remove drmP.h
commit eabd4e762217e9368fefc63308222388257cdbdc from
https://source.codeaurora.org/external/imx/linux-imx

API changes:
4e98f871bcff ("drm: delete drmP.h + drm_os_linux.h")

drivers/gpu/drm/imx/ipuv3/ipuv3-kms.c:15:10: fatal error: drm/drmP.h: No such file or directory
   15 | #include <drm/drmP.h>

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>