mtd/devices/m25p80: fix compile error in non-ppc platform
In non-ppc platform, compile error happens:
drivers/mtd/devices/m25p80.c: In function 'parse_flash_partition':
drivers/mtd/devices/m25p80.c:840: error: 'struct dev_archdata' has no member named 'of_node'
scripts/Makefile.build:313: *** [drivers/mtd/devices/m25p80.o] Error 1
scripts/Makefile.build:365: *** [drivers/mtd/devices] Error 2

function parse_flash_partition is introduced by fsl spi driver, so
use CONFIG_SPI_FSL_LIB to restrict it here.

Signed-off-by: Weiwei Wang <weiwei.wang@windriver.com>