drm: xlnx: Enabled CRYPTO_AES library when HDCP is enabled in TX Subsystems
commit 890da57644e49cd1a410955b1e032086771c3f11 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.1

Enabled CRYPTO_AES Kconfig to resolve the below
compilation warning."`xlnx_hdcp2x_tx_aes128_encrypt':
xlnx_hdcp2x_crypt.c.text+0x364): undefined reference to `aes_expandkey'"

Above library is not enabled by default in xilinx_versal_defconfig.
So added this config parameter in HDCP Kconfig to enable automatically
when HDCP is enabled.

This library is used in HDCP driver to perform AES
calculations and SHA operations in the process of generating encryption
and decryption keys.

Signed-off-by: Lakshmi Prasanna Eachuri <lakshmi.prasanna.eachuri@amd.com>
Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>