LF-3359 drm/imx: dpu: crtc: Pass the full state to CRTC atomic hooks
commit fbcd332cf8efbc86f5375cf8d7f628e30caa1d46 from
https://github.com/nxp-imx/linux-imx

drm atomic state to them.  So, the DPU CRTC driver should change accordingly,
otherwise there would be build break.

f6ebe9f9c923 ("drm/atomic: Pass the full state to CRTC atomic begin and flush")
29b77ad7b9ca ("drm/atomic: Pass the full state to CRTC atomic_check")
351f950db4ab ("drm/atomic: Pass the full state to CRTC atomic enable/disable")

This patch fixes build break for next-20210104 upgrade:
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1096:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .atomic_check = dpu_crtc_atomic_check,
                  ^~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1096:18: note: (near initialization for ‘dpu_helper_funcs.atomic_check’)
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1097:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .atomic_begin = dpu_crtc_atomic_begin,
                  ^~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1097:18: note: (near initialization for ‘dpu_helper_funcs.atomic_begin’)
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1098:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .atomic_flush = dpu_crtc_atomic_flush,
                  ^~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1098:18: note: (near initialization for ‘dpu_helper_funcs.atomic_flush’)
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1099:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .atomic_enable = dpu_crtc_atomic_enable,
                   ^~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1099:19: note: (near initialization for ‘dpu_helper_funcs.atomic_enable’)
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1100:20: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .atomic_disable = dpu_crtc_atomic_disable,
                    ^~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/dpu/dpu-crtc.c:1100:20: note: (near initialization for ‘dpu_helper_funcs.atomic_disable’)

Reviewed-by: Laurentiu Palcu <laurentiu.palcu@oss.nxp.com>
Signed-off-by: Liu Ying <victor.liu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>