net: stmmac: Fix build error too few parameters
Since commit ed7e211b6786 ("net: stmmac: fix FPE events losing")
adds the fpe_cfg parameter, add it to avoid build errors.

error: too few arguments to function 'priv->hw->mac->fpe_send_mpacket'

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>